import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import type { SocialHousingConstructionProgressRecord, SocialHousingConstructionProgressSummary, SocialHousingConstructionStageCategory } from '../src/models.ts';
import { updateConversionReport, writeJson } from './data.ts';
const input = 'data/raw/social-housing-construction-progress/source.json'; const out = 'public/data/social-housing-construction-progress';
const clean = (v: unknown) => { const s = String(v ?? '').trim(); return s || undefined; }; const norm = (v?: string) => v?.replace(/\s+/g, '').toLowerCase();
const num = (v: unknown) => { const n = Number(String(v ?? '').replace(/,/g, '')); return Number.isFinite(n) && n >= 0 ? n : undefined; };
export function stage(raw?: string): SocialHousingConstructionStageCategory { if (!raw) return 'unknown'; if (raw.includes('規劃')) return 'planning'; if (raw.includes('施工') || raw.includes('待開工')) return 'under_construction'; if (raw.includes('完工')) return 'completed'; if (raw.includes('入住')) return 'occupied'; if (raw.includes('設計')) return 'design'; if (raw.includes('招標')) return 'tendering'; return 'other'; }
export function convertSocialHousingRows(rows: Array<Record<string, unknown>>) { let invalidCoordinateCount=0, invalidNumberCount=0, missingNameCount=0, duplicateCount=0, unknownProgressCount=0; const seen=new Set<string>(); const records: SocialHousingConstructionProgressRecord[]=[];
for (const row of rows) { const projectName=clean(row.name), districtName=clean(row.distict ?? row.district), address=clean(row.address), latitudeRaw=clean(row.lat), longitudeRaw=clean(row.lng), latitude=num(latitudeRaw), longitude=num(longitudeRaw), plannedHouseholds=num(row.houseHolds), residentPopulation=num(row.persons), constructionStage=clean(row.progress), constructionStageCategory=stage(constructionStage); const hasValidCoordinates=latitude!==undefined&&longitude!==undefined&&latitude>=24.85&&latitude<=25.30&&longitude>=121.30&&longitude<=121.80; if(!hasValidCoordinates) invalidCoordinateCount++; if((clean(row.houseHolds)&&plannedHouseholds===undefined)||(clean(row.persons)&&residentPopulation===undefined)) invalidNumberCount++; if(!projectName) missingNameCount++; if(constructionStageCategory==='other'||constructionStageCategory==='unknown') unknownProgressCount++; const key=`${norm(projectName)}|${norm(address)}`; if(projectName&&seen.has(key)){duplicateCount++;continue;} if(projectName)seen.add(key); records.push({id:`${norm(projectName)??'unnamed'}-${records.length+1}`,module:'social_housing_construction_progress',projectName,projectNameNormalized:norm(projectName),districtName,districtNameNormalized:norm(districtName),address,addressNormalized:norm(address),latitudeRaw,longitudeRaw,latitude,longitude,hasValidCoordinates,plannedHouseholdsRaw:clean(row.houseHolds),plannedHouseholds,plannedHouseholdsNumber:plannedHouseholds,residentPopulationRaw:clean(row.persons),residentPopulation,residentPopulationNumber:residentPopulation,floorDescription:clean(row.floors),floorNumbers:(clean(row.floors)?.match(/\d+(?:\.\d+)?/g)??[]).map(Number),constructionStage,constructionStageNormalized:norm(constructionStage),constructionStageCategory,personsPerHousehold:residentPopulation!==undefined&&plannedHouseholds&&plannedHouseholds>0?residentPopulation/plannedHouseholds:undefined,sourceRaw:row}); }
return {records,quality:{invalidCoordinateCount,invalidNumberCount,missingNameCount,duplicateCount,unknownProgressCount}}; }
export function summary(records: SocialHousingConstructionProgressRecord[], dataQuality: SocialHousingConstructionProgressSummary['dataQuality']): SocialHousingConstructionProgressSummary { const byDistrict=[...new Set(records.map(r=>r.districtName).filter((x):x is string=>!!x))].map(d=>{const a=records.filter(r=>r.districtName===d);return {districtName:d,recordCount:a.length,plannedHouseholds:a.reduce((s,r)=>s+(r.plannedHouseholds??0),0),residentPopulation:a.reduce((s,r)=>s+(r.residentPopulation??0),0)}}).sort((a,b)=>b.recordCount-a.recordCount); const byStage=(['planning','design','tendering','under_construction','completed','occupied','other','unknown'] as const).map(constructionStageCategory=>({constructionStageCategory,recordCount:records.filter(r=>r.constructionStageCategory===constructionStageCategory).length})); return {totalProjects:records.length,validCoordinateCount:records.filter(r=>r.hasValidCoordinates).length,districtCount:byDistrict.length,totalPlannedHouseholds:records.reduce((s,r)=>s+(r.plannedHouseholds??0),0),totalResidentPopulation:records.reduce((s,r)=>s+(r.residentPopulation??0),0),underConstructionCount:byStage.find(x=>x.constructionStageCategory==='under_construction')!.recordCount,completedOrOccupiedCount:byStage.filter(x=>x.constructionStageCategory==='completed'||x.constructionStageCategory==='occupied').reduce((s,x)=>s+x.recordCount,0),districtWithMostProjects:byDistrict[0]?.districtName,districtWithMostPlannedHouseholds:[...byDistrict].sort((a,b)=>b.plannedHouseholds-a.plannedHouseholds)[0]?.districtName,builtAt:new Date().toISOString(),byStage,byDistrict,dataQuality}; }
export async function convertSocialHousingConstructionProgress(){const rows=JSON.parse(await readFile(input,'utf8')) as Array<Record<string,unknown>>; const result=convertSocialHousingRows(rows); const data=summary(result.records,result.quality); await writeJson(`${out}/records.json`,result.records); await writeJson(`${out}/summary.json`,data); await updateConversionReport({dataset:'臺北市社會住宅興建工程進度',file:input,status:'converted',sourceUrl:'https://hms.udd.gov.taipei/api/BigData/project',notes:[`${result.records.length} projects`,JSON.stringify(result.quality),'Official coordinates are only used as point markers; no polygons or site boundaries.']});return{records:result.records,summary:data};}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href) console.log((await convertSocialHousingConstructionProgress()).records.length);
