import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import type { MunicipalIdlePropertyLeaseTenderRecord, MunicipalIdlePropertyLeaseTenderSummary } from '../src/models.ts';
import { getColumn, listCsvFiles, readCsv, updateConversionReport, writeJson, type CsvRow } from './data.ts';

const directory = 'data/raw/municipal-idle-property-lease-tenders';
const source = '臺北市市有閒置房地出租招標結果';
const sourceAgency = '臺北市政府財政局';
const sourceUrl = 'https://data.taipei/dataset/detail?id=be46d539-5a32-4d12-9022-76228006b0e8';
const clean = (value: unknown) => { const text = String(value ?? '').replace(/\u3000/g, ' ').trim(); return text && !['-', '--', 'null', 'nan'].includes(text.toLowerCase()) ? text : undefined; };
const normalize = (value: string | undefined) => value?.replace(/\s+/g, '').replace(/[，、,.;；]/g, '');
const parseValue = (raw: string | undefined) => { const text = clean(raw); if (!text) return undefined; const match = text.replace(/[，,\s]/g, '').match(/-?\d+(?:\.\d+)?/); const value = match ? Number(match[0]) : NaN; return Number.isFinite(value) ? value : undefined; };
const parseYear = (raw: string | undefined) => { const value = parseValue(raw); if (value === undefined || !Number.isInteger(value)) return undefined; return value < 1911 ? { year: value + 1911, rocYear: value } : { year: value }; };
const districtFromLocation = (value: string | undefined) => value?.match(/(?:臺|台|新北)北市([\u4e00-\u9fff]{2,3}區)/)?.[1];
const usableAddress = (value: string | undefined) => !!value && /(?:路|街|大道)(?:[一二三四五六七八九十0-9]+段)?(?:[\u4e00-\u9fff0-9]+巷)?(?:[\u4e00-\u9fff0-9]+弄)?\d+(?:之\d+)?號/.test(value) && !/地號/.test(value);
const median = (values: number[]) => { const sorted = [...values].sort((a, b) => a - b); const middle = Math.floor(sorted.length / 2); return sorted.length ? (sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2) : undefined; };
const total = (records: MunicipalIdlePropertyLeaseTenderRecord[], key: 'leasedAreaSquareMeters' | 'reserveRent' | 'awardedRent') => records.reduce((sum, record) => sum + (record[key] ?? 0), 0);

export function makeMunicipalIdlePropertyLeaseTenderRecord(row: CsvRow, index: number) {
  const sourceSequenceNumberRaw = clean(getColumn(row, ['序號'])); const caseNameRaw = clean(getColumn(row, ['案件'])); const yearRaw = clean(getColumn(row, ['年度']));
  const propertyLocationRaw = clean(getColumn(row, ['建物門牌/地號'])); const leasedAreaSquareMetersRaw = clean(getColumn(row, ['出租面積_㎡'])); const reserveRentRaw = clean(getColumn(row, ['標租底價_元'])); const awardedRentRaw = clean(getColumn(row, ['得標價_元']));
  const parsedYear = parseYear(yearRaw); const leasedAreaSquareMeters = parseValue(leasedAreaSquareMetersRaw); const reserveRent = parseValue(reserveRentRaw); const awardedRent = parseValue(awardedRentRaw);
  const premiumAmount = reserveRent !== undefined && awardedRent !== undefined ? awardedRent - reserveRent : undefined;
  const premiumRate = premiumAmount !== undefined && reserveRent !== undefined && reserveRent > 0 ? premiumAmount / reserveRent : undefined;
  const mapQuery = usableAddress(propertyLocationRaw) ? propertyLocationRaw : undefined;
  return { record: { id: createHash('sha1').update(JSON.stringify(row)).digest('hex').slice(0, 16), module: 'municipal_idle_property_lease_tenders' as const, source, sourceAgency, sourceRaw: row, sourceSequenceNumberRaw, caseNameRaw, yearRaw, propertyLocationRaw, leasedAreaSquareMetersRaw, reserveRentRaw, awardedRentRaw, year: parsedYear?.year, rocYear: parsedYear?.rocYear, caseNameNormalized: normalize(caseNameRaw), propertyLocationNormalized: normalize(propertyLocationRaw), leasedAreaSquareMeters, reserveRent, awardedRent, premiumAmount, premiumRate, reserveRentPerSquareMeter: reserveRent !== undefined && leasedAreaSquareMeters && leasedAreaSquareMeters > 0 ? reserveRent / leasedAreaSquareMeters : undefined, awardedRentPerSquareMeter: awardedRent !== undefined && leasedAreaSquareMeters && leasedAreaSquareMeters > 0 ? awardedRent / leasedAreaSquareMeters : undefined, hasAwardedRent: awardedRent !== undefined, districtNameFromLocation: districtFromLocation(propertyLocationRaw), externalMapQuery: mapQuery } satisfies MunicipalIdlePropertyLeaseTenderRecord, invalidYear: !!yearRaw && !parsedYear, invalidAmount: [reserveRentRaw, awardedRentRaw].some((raw) => !!raw && parseValue(raw) === undefined), invalidArea: !!leasedAreaSquareMetersRaw && leasedAreaSquareMeters === undefined, missingFields: [sourceSequenceNumberRaw, caseNameRaw, yearRaw, propertyLocationRaw, leasedAreaSquareMetersRaw, reserveRentRaw, awardedRentRaw].filter((value) => !value).length };
}

export function buildMunicipalIdlePropertyLeaseTenderSummary(records: MunicipalIdlePropertyLeaseTenderRecord[], dataQuality: MunicipalIdlePropertyLeaseTenderSummary['dataQuality']): MunicipalIdlePropertyLeaseTenderSummary {
  const years = [...new Set(records.map((record) => record.year).filter((value): value is number => value !== undefined))].sort((a, b) => a - b);
  const awarded = records.map((record) => record.awardedRent).filter((value): value is number => value !== undefined); const awardedPerSqm = records.map((record) => record.awardedRentPerSquareMeter).filter((value): value is number => value !== undefined); const premiums = records.map((record) => record.premiumRate).filter((value): value is number => value !== undefined);
  const distribution = (values: number[], cuts: number[], suffix: string) => cuts.map((cut, index) => ({ label: index === cuts.length - 1 ? `${cut}${suffix}+` : `${cut}${suffix}–${cuts[index + 1]}${suffix}`, recordCount: values.filter((value) => value >= cut && (index === cuts.length - 1 || value < cuts[index + 1])).length }));
  const district = new Map<string, number>(); for (const record of records) if (record.districtNameFromLocation) district.set(record.districtNameFromLocation, (district.get(record.districtNameFromLocation) ?? 0) + 1);
  return { totalRecords: records.length, latestYear: years.at(-1), totalLeasedAreaSquareMeters: total(records, 'leasedAreaSquareMeters'), totalReserveRent: total(records, 'reserveRent'), totalAwardedRent: total(records, 'awardedRent'), recordsWithAwardedRent: awarded.length, medianAwardedRent: median(awarded), medianAwardedRentPerSquareMeter: median(awardedPerSqm), averagePremiumRate: premiums.length ? premiums.reduce((sum, value) => sum + value, 0) / premiums.length : undefined, highestAwardedRent: awarded.length ? Math.max(...awarded) : undefined, byYear: years.map((year) => { const items = records.filter((record) => record.year === year); return { year, recordCount: items.length, totalLeasedAreaSquareMeters: total(items, 'leasedAreaSquareMeters'), totalReserveRent: total(items, 'reserveRent'), totalAwardedRent: total(items, 'awardedRent') }; }), premiumRateDistribution: distribution(premiums.map((value) => value * 100), [-100, 0, 25, 50, 100], '%'), awardedRentPerSquareMeterDistribution: distribution(awardedPerSqm, [0, 1_000, 5_000, 10_000, 25_000], ''), byDistrict: [...district].map(([districtName, recordCount]) => ({ districtName, recordCount })).sort((a, b) => b.recordCount - a.recordCount), dataQuality };
}

export async function convertMunicipalIdlePropertyLeaseTenders() {
  const file = (await listCsvFiles(directory)).at(-1); const rows = file ? await readCsv(file) : []; const seen = new Set<string>(); let invalidYearCount = 0; let invalidAmountCount = 0; let invalidAreaCount = 0; let duplicateCount = 0; let missingFieldCount = 0;
  const records = rows.flatMap((row, index) => { const result = makeMunicipalIdlePropertyLeaseTenderRecord(row, index + 1); invalidYearCount += Number(result.invalidYear); invalidAmountCount += Number(result.invalidAmount); invalidAreaCount += Number(result.invalidArea); missingFieldCount += result.missingFields; const key = [result.record.yearRaw, result.record.caseNameRaw, result.record.propertyLocationRaw, result.record.reserveRentRaw, result.record.awardedRentRaw].join('|'); if (seen.has(key)) { duplicateCount += 1; return []; } seen.add(key); return [result.record]; });
  const summary = buildMunicipalIdlePropertyLeaseTenderSummary(records, { invalidYearCount, invalidAmountCount, invalidAreaCount, duplicateCount, missingFieldCount, recordsWithUsableMapQuery: records.filter((record) => record.externalMapQuery).length });
  await writeJson('public/data/municipal-idle-property-lease-tenders/records.json', records); await writeJson('public/data/municipal-idle-property-lease-tenders/summary.json', summary);
  await updateConversionReport({ dataset: source, file: file ?? directory, status: file ? 'converted' : 'missing', sourceUrl, notes: [`${records.length} normalized records`, `Invalid years: ${invalidYearCount}; invalid amounts: ${invalidAmountCount}; invalid areas: ${invalidAreaCount}; missing fields: ${missingFieldCount}; duplicates removed: ${duplicateCount}.`, 'All source values are retained as raw strings. No geocoding or exact map markers are generated; map links require a usable street address.'] }); return { records, summary };
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) { const { records } = await convertMunicipalIdlePropertyLeaseTenders(); console.log(`municipal idle-property lease tenders: ${records.length}`); }
