import { createHash } from 'node:crypto';
import { getColumn, listCsvFiles, readCsv, writeJson, type CsvRow } from './data.ts';

const text = (value: unknown) => { const result = String(value ?? '').replace(/\u3000/g, ' ').trim(); return result && !['-', '--', 'null', 'nan'].includes(result.toLowerCase()) ? result : undefined; };
const number = (value: string | undefined) => { const match = text(value)?.replace(/[，,\s]/g, '').match(/\d+(?:\.\d+)?/)?.[0]; const result = match ? Number(match) : NaN; return Number.isFinite(result) ? result : undefined; };
const district = (value: string | undefined) => value?.match(/(中正區|大同區|中山區|松山區|大安區|萬華區|信義區|士林區|北投區|內湖區|南港區|文山區)/)?.[1];
export const makeMunicipalPublicLandRecord = (row: CsvRow) => { const managingAgency = text(getColumn(row, ['管理機關'])); const landIdentifier = text(getColumn(row, ['土地標示名稱'])); const parcelAreaSquareMeters = number(getColumn(row, ['宗地面積（平方公尺）', '宗地面積(平方公尺)', '宗地面積'])); const ownershipShareAreaSquareMeters = number(getColumn(row, ['持分面積（平方公尺）', '持分面積(平方公尺)', '持分面積'])); const recordedValue = number(getColumn(row, ['列帳金額（元）', '列帳金額(元)', '列帳金額'])); return { id: createHash('sha1').update(JSON.stringify(row)).digest('hex').slice(0, 16), managingAgency, landIdentifier, parcelAreaSquareMeters, ownershipShareAreaSquareMeters, recordedValue, recordedValuePerOwnedSquareMeter: recordedValue !== undefined && ownershipShareAreaSquareMeters && ownershipShareAreaSquareMeters > 0 ? recordedValue / ownershipShareAreaSquareMeters : undefined, ownershipShareRatio: ownershipShareAreaSquareMeters !== undefined && parcelAreaSquareMeters && parcelAreaSquareMeters > 0 ? ownershipShareAreaSquareMeters / parcelAreaSquareMeters : undefined, districtName: district(landIdentifier), sourceRaw: row }; };
export async function convertMunicipalPublicLandInventory() { const file = (await listCsvFiles('data/raw/municipal-public-land-inventory')).at(-1); const rows = file ? await readCsv(file) : []; const seen = new Set<string>(); let duplicateCount = 0; const records = rows.flatMap((row) => { const record = makeMunicipalPublicLandRecord(row); const key = [record.managingAgency, record.landIdentifier, record.parcelAreaSquareMeters, record.ownershipShareAreaSquareMeters, record.recordedValue].join('|'); if (seen.has(key)) { duplicateCount += 1; return []; } seen.add(key); return [record]; }); const areas = records.map((record) => record.parcelAreaSquareMeters).filter((value): value is number => value !== undefined).sort((a,b) => a-b); const median = areas.length ? areas[Math.floor(areas.length / 2)] : undefined; await writeJson('public/data/municipal-public-land-inventory/records.json', records); await writeJson('public/data/municipal-public-land-inventory/summary.json', { totalRecords: records.length, medianParcelAreaSquareMeters: median, dataQuality: { duplicateCount, invalidAreaCount: 0, invalidAmountCount: 0, missingAgencyCount: records.filter((record) => !record.managingAgency).length, missingLandIdentifierCount: records.filter((record) => !record.landIdentifier).length } }); return records; }
if (process.argv[1]?.endsWith('convertMunicipalPublicLandInventory.ts')) console.log((await convertMunicipalPublicLandInventory()).length);
