import { createHash } from 'node:crypto';
import { getColumn, listCsvFiles, readCsv, writeJson, type CsvRow } from './data.ts';
export type MunicipalPropertyPortfolioRecord = { id:string; rocYearRaw:string; rocYear:number|null; gregorianYear:number|null; monthRaw:string; month:number|null; propertyNatureRaw:string; propertyNature:string; itemRaw:string; item:string; amountRaw:string; amountTwd:number|null; period:string|null; hasValidPeriod:boolean; hasValidAmount:boolean; sourceRaw:CsvRow };
const clean=(v:unknown)=>String(v??'').replace(/[\u3000\s]+/g,' ').trim();
export function parsePortfolioYear(raw:string) { const value=clean(raw); if (!/^\d{3,4}$/.test(value)) return { rocYear:null, gregorianYear:null }; const year=Number(value); return year < 1911 ? { rocYear:year, gregorianYear:year+1911 } : { rocYear:null, gregorianYear:year }; }
export function parsePortfolioMonth(raw:string) { const value=clean(raw); return /^\d{1,2}$/.test(value) && Number(value)>=1 && Number(value)<=12 ? Number(value) : null; }
export function parsePortfolioAmount(raw:string) { const value=clean(raw); if (!value || /^(?:-|--|n\/a)$/i.test(value)) return null; const normalized=value.replace(/[\s,，$￥]/g,'').replace(/^NT\$/i,''); return /^\d+(?:\.\d+)?$/.test(normalized) && Number(normalized)>=0 ? Number(normalized) : null; }
export function stablePortfolioId(record: Pick<MunicipalPropertyPortfolioRecord,'gregorianYear'|'month'|'propertyNature'|'item'>, raw:CsvRow) { const key=[record.gregorianYear,record.month,record.propertyNature,record.item].join('-'); return key && !key.includes('null') ? `municipal-property-${key}` : `municipal-property-${createHash('sha1').update(JSON.stringify(raw)).digest('hex').slice(0,12)}`; }
export function convertMunicipalPropertyPortfolioRows(rows:CsvRow[]): MunicipalPropertyPortfolioRecord[] { const seen=new Map<string,number>(); return rows.map(sourceRaw=>{ const rocYearRaw=clean(getColumn(sourceRaw,['年度','Year'])); const monthRaw=clean(getColumn(sourceRaw,['月份','Month'])); const propertyNatureRaw=clean(getColumn(sourceRaw,['財產性質別','PropertyNature'])); const itemRaw=clean(getColumn(sourceRaw,['項目','Item'])); const amountRaw=clean(getColumn(sourceRaw,['金額（元）','金額(元)','Amount'])); const year=parsePortfolioYear(rocYearRaw), month=parsePortfolioMonth(monthRaw), amountTwd=parsePortfolioAmount(amountRaw); const base={rocYearRaw,rocYear:year.rocYear,gregorianYear:year.gregorianYear,monthRaw,month,propertyNatureRaw,propertyNature:propertyNatureRaw||'unknown',itemRaw,item:itemRaw||'unknown',amountRaw,amountTwd,period:year.gregorianYear&&month?`${year.gregorianYear}-${String(month).padStart(2,'0')}`:year.gregorianYear?String(year.gregorianYear):null,hasValidPeriod:Boolean(year.gregorianYear&&month),hasValidAmount:amountTwd!==null,sourceRaw}; const id=stablePortfolioId(base,sourceRaw); const count=seen.get(id)??0; seen.set(id,count+1); return {...base,id:count?`${id}-${createHash('sha1').update(JSON.stringify(sourceRaw)).digest('hex').slice(0,8)}`:id}; }); }
export function buildMunicipalPropertyPortfolioSummary(records:MunicipalPropertyPortfolioRecord[]) { const valid=records.filter(r=>r.hasValidPeriod&&r.hasValidAmount); const sum=(items:MunicipalPropertyPortfolioRecord[])=>items.reduce((total,r)=>total+(r.amountTwd??0),0); const years=[...new Set(valid.map(r=>r.gregorianYear!))].sort((a,b)=>a-b); const byYear=years.map(year=>({year,amountTwd:sum(valid.filter(r=>r.gregorianYear===year))})); const totalRows=records.filter(r=>/^(?:合計|總計|小計)/.test(r.itemRaw)); const combos=valid.map(r=>`${r.period}|${r.propertyNature}|${r.item}`); return { totalRecords:records.length, validAmountCount:valid.length, years, byYear, propertyNatures:[...new Set(records.map(r=>r.propertyNatureRaw).filter(Boolean))], items:[...new Set(records.map(r=>r.itemRaw).filter(Boolean))], aggregation:{officialTotalRowsDetected:totalRows.length>0,totalRowLabels:[...new Set(totalRows.map(r=>r.itemRaw))],additiveItems:[...new Set(valid.filter(r=>!totalRows.includes(r)).map(r=>r.itemRaw))],excludedSubtotalItems:[...new Set(totalRows.map(r=>r.itemRaw))]}, dataQuality:{missingYearCount:records.filter(r=>r.gregorianYear===null).length,invalidMonthCount:records.filter(r=>r.month===null).length,missingPropertyNatureCount:records.filter(r=>!r.propertyNatureRaw).length,missingItemCount:records.filter(r=>!r.itemRaw).length,missingAmountCount:records.filter(r=>!r.amountRaw).length,invalidAmountCount:records.filter(r=>r.amountRaw&&r.amountTwd===null).length,negativeAmountCount:records.filter(r=>(r.amountTwd??0)<0).length,duplicateCombinationCount:combos.length-new Set(combos).size} }; }
export async function convertMunicipalPropertyPortfolio(){const file=(await listCsvFiles('data/raw/municipal-property-portfolio')).at(-1);const records=convertMunicipalPropertyPortfolioRows(file?await readCsv(file):[]); const summary=buildMunicipalPropertyPortfolioSummary(records); await writeJson('public/data/municipal-property-portfolio/records.json',records);await writeJson('public/data/municipal-property-portfolio/summary.json',summary);await writeJson('public/data/municipal-property-portfolio/metadata.json',{sourceUrl:'https://data.taipei/dataset/detail?id=fb19bfcb-33e5-4f82-8d0e-2460152282c4',sourceAgency:'臺北市政府財政局',coverage:'2021-01-01 through 2025-12-31',updateFrequency:'annual',aggregation:summary.aggregation,amountInterpretation:'Source-recorded municipal property amount'});return records;}
if(process.argv[1]?.endsWith('convertMunicipalPropertyPortfolio.ts'))console.log((await convertMunicipalPropertyPortfolio()).length);
