import { createHash } from 'node:crypto'; import { getColumn,listCsvFiles,readCsv,writeJson,type CsvRow } from './data.ts';
export type CivilRecord={id:string;cityCode:string;periodRaw:string;rocYear:number|null;month:number|null;gregorianYear:number|null;period:string|null;categoryRaw:string;category:string;categoryGroup:'overall'|'materials'|'labor'|'equipment'|'unknown';indexValueRaw:string;indexValue:number|null;yearOverYearRaw:string;yearOverYearRate:number|null;hasValidPeriod:boolean;hasValidIndex:boolean;hasValidYoY:boolean;sourceRaw:CsvRow};
const clean=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim(); const map:Record<string,[string,CivilRecord['categoryGroup']]>= {'總指數':['overall','overall'],'材料類':['materials','materials'],'水泥及其製品類':['cement_products','materials'],'砂石及級配類':['aggregates','materials'],'磚瓦瓷類':['brick_tile_ceramic','materials'],'金屬製品類':['metal_products','materials'],'木材及其製品類':['wood_products','materials'],'塑膠製品類':['plastic_products','materials'],'油漆塗料類':['paint_coatings','materials'],'機電設備類':['electromechanical_equipment','materials'],'瀝青及其製品類':['asphalt_products','materials'],'雜項材料類':['misc_materials','materials'],'勞務類':['labor_services','labor'],'工資類':['wages','labor'],'機具設備租金類':['equipment_rental','equipment']};
export function parseCivilPeriod(raw:string){const match=clean(raw).match(/^(\d{2,3})年\s*(\d{1,2})月$/);if(!match)return{rocYear:null,month:null,gregorianYear:null,period:null};const rocYear=Number(match[1]),month=Number(match[2]);if(!rocYear||month<1||month>12)return{rocYear:null,month:null,gregorianYear:null,period:null};const gregorianYear=rocYear+1911;return{rocYear,month,gregorianYear,period:`${gregorianYear}-${String(month).padStart(2,'0')}`};}
export function parseCivilNumber(raw:string,percentage=false){const value=clean(raw).replace('%','');if(!value||/^(--|-|n\/a)$/i.test(value))return null;const number=Number(value.replace(/,/g,''));return Number.isFinite(number)&&(percentage||number>=0)?number:null;}
export function convertCivilEngineeringPriceRows(rows:CsvRow[]):CivilRecord[]{return rows.map(sourceRaw=>{const cityCode=clean(getColumn(sourceRaw,['縣市別代碼']));const periodRaw=clean(getColumn(sourceRaw,['統計期']));const categoryRaw=clean(getColumn(sourceRaw,['基本分類']));const indexValueRaw=clean(getColumn(sourceRaw,['原始值[統計數值]']));const yearOverYearRaw=clean(getColumn(sourceRaw,['年增率[%]']));const period=parseCivilPeriod(periodRaw), category=map[categoryRaw]??['unknown','unknown'];const indexValue=parseCivilNumber(indexValueRaw),yearOverYearRate=parseCivilNumber(yearOverYearRaw,true);return{id:`civil-price-${cityCode}-${period.period??createHash('sha1').update(JSON.stringify(sourceRaw)).digest('hex').slice(0,8)}-${category[0]}`,cityCode,periodRaw,...period,categoryRaw,category:category[0],categoryGroup:category[1],indexValueRaw,indexValue,yearOverYearRaw,yearOverYearRate,hasValidPeriod:Boolean(period.period),hasValidIndex:indexValue!==null,hasValidYoY:yearOverYearRate!==null,sourceRaw};});}
export function buildCivilEngineeringPriceSummary(records:CivilRecord[]){const valid=records.filter(r=>r.hasValidPeriod);const periods=[...new Set(valid.map(r=>r.period!))].sort();const latest=periods.at(-1)??null;return{recordCount:records.length,categoryCount:new Set(records.map(r=>r.categoryRaw)).size,categories:[...new Set(records.map(r=>r.categoryRaw))],firstPeriod:periods[0]??null,latestPeriod:latest,missingPeriodCount:records.filter(r=>!r.hasValidPeriod).length,missingMonths:periods.filter((p,i)=>i&&new Date(`${p}-01`).getTime()-new Date(`${periods[i-1]}-01`).getTime()>32*86400000),latestRecords:records.filter(r=>r.period===latest),dataQuality:{missingCategory:records.filter(r=>!r.categoryRaw).length,unknownCategory:records.filter(r=>r.category==='unknown').length,missingIndex:records.filter(r=>r.indexValue===null).length,missingYoY:records.filter(r=>r.yearOverYearRate===null).length,duplicateCount:records.length-new Set(records.map(r=>`${r.cityCode}|${r.period}|${r.categoryRaw}`)).size}};}
export async function convertCivilEngineeringPriceIndex(){const file=(await listCsvFiles('data/raw/civil-engineering-price-index')).at(-1);const records=convertCivilEngineeringPriceRows(file?await readCsv(file):[]);const summary=buildCivilEngineeringPriceSummary(records);await writeJson('public/data/civil-engineering-price-index/records.json',records);await writeJson('public/data/civil-engineering-price-index/summary.json',summary);await writeJson('public/data/civil-engineering-price-index/metadata.json',{sourceUrl:'https://data.taipei/dataset/detail?id=e0cfb477-9dbd-4af2-a0a6-6cb132821584',sourceAgency:'臺北市政府主計處',coverage:`${summary.firstPeriod} through ${summary.latestPeriod}`,updateFrequency:'monthly',ingestedAt:new Date().toISOString(),...summary});return records;}
if(process.argv[1]?.endsWith('convertCivilEngineeringPriceIndex.ts'))console.log((await convertCivilEngineeringPriceIndex()).length);
