import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './models';

type RecordItem = { id:string; sourceRowNumber:number; lotNumberRaw:string; districtName:string; landSection:string; parcelNumber:string; areaSqmRaw:string; areaSqm:number|null; originalRegisteredHolderRaw:string; rightsShareRaw:string; rightsNumerator:number|null; rightsDenominator:number|null; rightsRatio:number|null; reservePriceRaw:string; reservePriceTwd:number|null; totalReservePriceRaw:string; totalReservePriceTwd:number|null; awardedPriceRaw:string; awardedPriceTwd:number|null; winningBidderRaw:string; priceDifferenceTwd:number|null; awardToReserveRatio:number|null; premiumDiscountPct:number|null; reservePricePerSqm:number|null; awardedPricePerSqm:number|null; hasValidArea:boolean; hasValidReservePrice:boolean; hasValidAwardedPrice:boolean; sourceRaw:Record<string,string>; inheritedLocator:Record<string,string> };
type Metadata = { totalRecords?:number; resourceUpdatedAt?:string; metadataUpdatedAt?:string; sourceUrl?:string; qualityCounts?:Record<string,number>; reservePriceFieldInterpretation?:string };
const base = import.meta.env.BASE_URL;
const missing = '—';
const median = (values: Array<number | null>) => { const items = values.filter((value): value is number => value !== null && Number.isFinite(value)).sort((a, b) => a - b); if (!items.length) return null; const middle = Math.floor(items.length / 2); return items.length % 2 ? items[middle] : (items[middle - 1] + items[middle]) / 2; };
const sum = (values: Array<number | null>) => values.reduce<number>((total, value) => total + (value ?? 0), 0);
const csvCell = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;
const numberInput = (value: string) => value === '' ? null : Number(value);

export function CadastralCleanupLandAuctionResults({ language }: { language: Language }) {
  const t = (zh: string, en: string) => language === 'zh' ? zh : en;
  const [records, setRecords] = useState<RecordItem[]>([]); const [metadata, setMetadata] = useState<Metadata>({});
  const [district, setDistrict] = useState(''); const [section, setSection] = useState(''); const [query, setQuery] = useState(''); const [bidder, setBidder] = useState(''); const [rights, setRights] = useState(''); const [validAward, setValidAward] = useState('');
  const [areaMin, setAreaMin] = useState(''); const [areaMax, setAreaMax] = useState(''); const [reserveMin, setReserveMin] = useState(''); const [reserveMax, setReserveMax] = useState(''); const [awardMin, setAwardMin] = useState(''); const [awardMax, setAwardMax] = useState(''); const [premiumMin, setPremiumMin] = useState(''); const [premiumMax, setPremiumMax] = useState('');
  const [page, setPage] = useState(1); const [sort, setSort] = useState<'lot'|'area'|'reserve'|'award'|'premium'>('lot'); const [showDetails, setShowDetails] = useState(false);
  useEffect(() => { Promise.all([fetch(`${base}data/cadastral-cleanup-land-auction-results/records.json`).then((r) => r.json()), fetch(`${base}data/cadastral-cleanup-land-auction-results/metadata.json`).then((r) => r.json())]).then(([items, info]) => { setRecords(items); setMetadata(info); }).catch(() => setRecords([])); }, []);
  const filtered = useMemo(() => {
    const min = (value: string) => numberInput(value); const q = query.trim().toLowerCase(); const bidderQuery = bidder.trim().toLowerCase();
    const between = (value: number | null, lower: number | null, upper: number | null) => (lower === null || (value ?? -Infinity) >= lower) && (upper === null || (value ?? Infinity) <= upper);
    return records.filter((record) => {
      const searchable = [record.districtName, record.landSection, record.parcelNumber, record.lotNumberRaw, record.originalRegisteredHolderRaw, record.rightsShareRaw, record.winningBidderRaw].join(' ').toLowerCase();
      const rightsKind = record.rightsRatio === 1 ? 'full' : record.rightsRatio !== null ? 'fraction' : record.rightsShareRaw ? 'other' : 'missing';
      return (!district || record.districtName === district) && (!section || record.landSection === section) && (!q || searchable.includes(q)) && (!bidderQuery || record.winningBidderRaw.toLowerCase().includes(bidderQuery)) && (!rights || rightsKind === rights) && (!validAward || String(record.hasValidAwardedPrice) === validAward)
        && between(record.areaSqm, min(areaMin), min(areaMax)) && between(record.totalReservePriceTwd, min(reserveMin), min(reserveMax)) && between(record.awardedPriceTwd, min(awardMin), min(awardMax)) && between(record.premiumDiscountPct, min(premiumMin), min(premiumMax));
    }).sort((a, b) => sort === 'lot' ? a.lotNumberRaw.localeCompare(b.lotNumberRaw, 'zh-Hant') : (b[sort === 'area' ? 'areaSqm' : sort === 'reserve' ? 'totalReservePriceTwd' : sort === 'award' ? 'awardedPriceTwd' : 'premiumDiscountPct'] ?? -Infinity) - (a[sort === 'area' ? 'areaSqm' : sort === 'reserve' ? 'totalReservePriceTwd' : sort === 'award' ? 'awardedPriceTwd' : 'premiumDiscountPct'] ?? -Infinity));
  }, [records, district, section, query, bidder, rights, validAward, areaMin, areaMax, reserveMin, reserveMax, awardMin, awardMax, premiumMin, premiumMax, sort]);
  useEffect(() => setPage(1), [district, section, query, bidder, rights, validAward, areaMin, areaMax, reserveMin, reserveMax, awardMin, awardMax, premiumMin, premiumMax, sort]);
  const districts = [...new Set(records.map((record) => record.districtName).filter(Boolean))].sort(); const sections = [...new Set(records.map((record) => record.landSection).filter(Boolean))].sort();
  const money = (value: number | null) => value === null ? missing : `NT$${Math.round(value).toLocaleString('zh-TW')}`; const area = (value: number | null) => value === null ? missing : `${value.toLocaleString('zh-TW', { maximumFractionDigits: 2 })} m²`; const percent = (value: number | null) => value === null ? missing : `${value.toLocaleString('zh-TW', { maximumFractionDigits: 1, signDisplay: 'always' })}%`;
  const awardRows = filtered.filter((record) => record.hasValidAwardedPrice); const premiumRows = awardRows.filter((record) => record.premiumDiscountPct !== null); const above = premiumRows.filter((record) => (record.premiumDiscountPct ?? 0) > 0).length; const at = premiumRows.filter((record) => record.premiumDiscountPct === 0).length; const below = premiumRows.filter((record) => (record.premiumDiscountPct ?? 0) < 0).length;
  const kpis = [[t('標售結果紀錄', 'Auction-result records'), String(filtered.length)], [t('行政區', 'Districts'), String(new Set(filtered.map((record) => record.districtName)).size)], [t('段小段', 'Land sections'), String(new Set(filtered.map((record) => record.landSection)).size)], [t('來源記載面積合計', 'Source-recorded area'), area(sum(filtered.map((record) => record.areaSqm)))], [t('來源總底價合計', 'Source total reserve'), money(sum(filtered.map((record) => record.totalReservePriceTwd)))], [t('來源決標金額合計', 'Source awarded amount'), money(sum(filtered.map((record) => record.awardedPriceTwd)))], [t('決標金額中位數', 'Median awarded price'), money(median(filtered.map((record) => record.awardedPriceTwd)))], [t('決標單價中位數', 'Median award / m²'), money(median(filtered.map((record) => record.awardedPricePerSqm)))], [t('溢折價中位數', 'Median premium / discount'), percent(median(premiumRows.map((record) => record.premiumDiscountPct)))], [t('高於底價', 'Above reserve'), String(above)], [t('等於底價', 'At reserve'), String(at)], [t('有效決標金額', 'Valid awards'), String(awardRows.length)]];
  const scatter = awardRows.flatMap((record) => record.totalReservePriceTwd === null || record.awardedPriceTwd === null ? [] : [{ ...record, x: record.totalReservePriceTwd, y: record.awardedPriceTwd }]);
  const bins = [-Infinity, 0, 10, 30, Infinity].map((upper, index, all) => ({ label: index === 0 ? '≤ 0%' : index === all.length - 1 ? '> 30%' : `${all[index - 1]}–${upper}%`, count: premiumRows.filter((record) => (record.premiumDiscountPct ?? 0) > (index ? all[index - 1] : -Infinity) && (record.premiumDiscountPct ?? 0) <= upper).length }));
  const districtData = [...new Set(filtered.map((record) => record.districtName))].filter(Boolean).map((name) => { const items = filtered.filter((record) => record.districtName === name); return { name, records: items.length, area: sum(items.map((record) => record.areaSqm)), awarded: sum(items.map((record) => record.awardedPriceTwd)), medianAwardPerSqm: median(items.map((record) => record.awardedPricePerSqm)) }; });
  const sectionData = [...new Set(filtered.map((record) => record.landSection))].filter(Boolean).map((name) => { const items = filtered.filter((record) => record.landSection === name); return { name, records: items.length, totalArea: sum(items.map((record) => record.areaSqm)), medianArea: median(items.map((record) => record.areaSqm)), medianRatio: median(items.map((record) => record.awardToReserveRatio)), awarded: sum(items.map((record) => record.awardedPriceTwd)) }; }).filter((item) => item.records >= 3).sort((a, b) => b.records - a.records);
  const bidderGroups = Object.values(awardRows.filter((record) => record.winningBidderRaw && record.winningBidderRaw !== '流標').reduce<Record<string, RecordItem[]>>((groups, record) => { (groups[record.winningBidderRaw] ??= []).push(record); return groups; }, {})); const repeatWins = bidderGroups.filter((items) => items.length > 1).flat().length;
  const quality = useMemo(() => { const parcel = new Map<string, RecordItem[]>(); filtered.forEach((record) => { const key = `${record.districtName}|${record.landSection}|${record.parcelNumber}`; parcel.set(key, [...(parcel.get(key) ?? []), record]); }); return [[t('缺少標號', 'Missing lot number'), filtered.filter((record) => !record.lotNumberRaw).length], [t('缺少行政區／段小段／地號', 'Missing locator fields'), filtered.filter((record) => !record.districtName || !record.landSection || !record.parcelNumber).length], [t('面積缺失或格式無效', 'Missing or malformed area'), filtered.filter((record) => !record.hasValidArea).length], [t('權利範圍缺失／不明確分數', 'Missing or ambiguous rights share'), filtered.filter((record) => !record.rightsShareRaw || (record.rightsShareRaw && record.rightsRatio === null)).length], [t('總底價缺失或格式無效', 'Missing or malformed total reserve'), filtered.filter((record) => !record.hasValidReservePrice).length], [t('決標金額格式無效', 'Malformed award amount'), filtered.filter((record) => record.awardedPriceRaw && !record.hasValidAwardedPrice).length], [t('低於總底價（請檢視）', 'Below total reserve (review)'), below], [t('重複行政區－段小段－地號', 'Repeated district-section-parcel'), [...parcel.values()].filter((items) => items.length > 1).length]]; }, [filtered, below, language]);
  const pages = Math.max(1, Math.ceil(filtered.length / 15)); const visible = filtered.slice((page - 1) * 15, page * 15);
  const exportCsv = () => { const header = ['Lot', 'District', 'Section', 'Parcel', 'Area m²', 'Original registered holder', 'Rights share', 'Reserve price', 'Total reserve price', 'Awarded price', 'Winning bidder']; const values = filtered.map((record) => [record.lotNumberRaw, record.districtName, record.landSection, record.parcelNumber, record.areaSqmRaw, record.originalRegisteredHolderRaw, record.rightsShareRaw, record.reservePriceRaw, record.totalReservePriceRaw, record.awardedPriceRaw, record.winningBidderRaw]); const blob = new Blob([[header, ...values].map((row) => row.map(csvCell).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'cadastral-cleanup-land-auction-results-filtered.csv'; link.click(); URL.revokeObjectURL(link.href); };
  const range = (label: string, minValue: string, setMin: (value: string) => void, maxValue: string, setMax: (value: string) => void) => <label><span>{label}</span><div className="range-inputs"><input type="number" min="0" value={minValue} onChange={(event) => setMin(event.target.value)} placeholder={t('最小值', 'Min')} /><input type="number" min="0" value={maxValue} onChange={(event) => setMax(event.target.value)} placeholder={t('最大值', 'Max')} /></div></label>;
  return <>
    <section className="section-intro auction-intro"><p className="eyebrow">{t('地政／歷史行政紀錄', 'LAND ADMINISTRATION / HISTORICAL RECORDS')}</p><h2>{t('地籍清理公告開標結果土地清冊', 'Cadastral Cleanup Land Auction Results')}</h2><p>{t('以來源記載的標售結果，探索地籍清理程序下的土地拍賣紀錄；不是一般不動產交易、現售標的、所有權查證或估價工具。', 'Explore source-recorded land-auction outcomes under the cadastral-cleanup process. This is not an ordinary transaction database, a current listing, title verification, or valuation tool.')}</p><p className="notice">{t('地號僅作表格與彙整分析：資料未提供座標或界址，本模組不會地理編碼、繪製地圖或推定目前權利狀態。', 'Parcel identifiers are used only for table and aggregate analysis. The source provides no coordinates or geometry, so this module does not geocode, map, or infer current rights.')}</p></section>
    <section className="analysis-list auction-filters"><div className="section-heading"><div><p className="eyebrow">{t('篩選器', 'FILTERS')}</p><h3>{t('縮小分析範圍', 'Focus the analysis')}</h3></div><button className="link-button" onClick={exportCsv}>{t('下載篩選 CSV', 'Export filtered CSV')}</button></div><div className="filter-grid"> <label><span>{t('行政區', 'District')}</span><select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="">{t('全部', 'All')}</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>{t('段小段', 'Land section')}</span><select value={section} onChange={(event) => setSection(event.target.value)}><option value="">{t('全部', 'All')}</option>{sections.map((item) => <option key={item}>{item}</option>)}</select></label><label className="search-field"><span>{t('關鍵字', 'Keyword')}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('行政區、段、地號、標號或姓名', 'District, section, parcel, lot, or name')} /></label><label><span>{t('權利範圍類型', 'Rights-share type')}</span><select value={rights} onChange={(event) => setRights(event.target.value)}><option value="">{t('全部', 'All')}</option><option value="full">{t('全部權利', 'Full')}</option><option value="fraction">{t('分數', 'Fraction')}</option><option value="other">{t('其他文字', 'Other text')}</option><option value="missing">{t('缺失', 'Missing')}</option></select></label><label><span>{t('得標人精確搜尋', 'Winning bidder search')}</span><input value={bidder} onChange={(event) => setBidder(event.target.value)} /></label><label><span>{t('有有效決標金額', 'Valid awarded price')}</span><select value={validAward} onChange={(event) => setValidAward(event.target.value)}><option value="">{t('全部', 'All')}</option><option value="true">{t('是', 'Yes')}</option><option value="false">{t('否', 'No')}</option></select></label>{range(t('面積（m²）', 'Area (m²)'), areaMin, setAreaMin, areaMax, setAreaMax)}{range(t('總底價（NT$）', 'Total reserve (NT$)'), reserveMin, setReserveMin, reserveMax, setReserveMax)}{range(t('決標金額（NT$）', 'Awarded price (NT$)'), awardMin, setAwardMin, awardMax, setAwardMax)}{range(t('溢價／折價（%）', 'Premium / discount (%)'), premiumMin, setPremiumMin, premiumMax, setPremiumMax)}</div></section>
    <section><div className="section-heading"><div><p className="eyebrow">{t('拍賣概覽', 'AUCTION OVERVIEW')}</p><h3>{t('來源記載摘要', 'Source-recorded summary')}</h3></div><span className="muted">{t('資料更新', 'Updated')}: {metadata.resourceUpdatedAt ?? missing}</span></div><div className="metric-strip">{kpis.map(([label, value]) => <article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><p className="muted">{t('總額與中位數會排除缺失或無法解析的數值；目前篩選範圍中，未納入有效決標金額的紀錄：', 'Totals and medians exclude missing or unparseable values. Records without a valid award in this filtered view: ')}{filtered.length - awardRows.length}</p></section>
    <section className="analysis-list"><div className="section-heading"><div><p className="eyebrow">{t('動態洞察', 'DYNAMIC INSIGHTS')}</p><h3>{t('目前篩選結果的拍賣結果描述', 'Auction-outcome description for current filters')}</h3></div></div><div className="insight-grid"><article><h4>{t('溢價／折價', 'Premium / discount')}</h4><p>{t(`在目前篩選的地籍清理標售結果中，決標價相對來源記載總底價的中位數為 ${percent(median(premiumRows.map((record) => record.premiumDiscountPct)))}。`, `Among currently filtered cadastral-cleanup auction results, the median awarded price was ${percent(median(premiumRows.map((record) => record.premiumDiscountPct)))} relative to the source-recorded total reserve price.`)}</p><small>{t(`平均 ${percent(premiumRows.length ? sum(premiumRows.map((record) => record.premiumDiscountPct)) / premiumRows.length : null)}；高於 ${above}、等於 ${at}、低於 ${below}。`, `Average ${percent(premiumRows.length ? sum(premiumRows.map((record) => record.premiumDiscountPct)) / premiumRows.length : null)}; above ${above}, at ${at}, below ${below}.`)}</small></article><article><h4>{t('得標溢價分布', 'Award premium distribution')}</h4><p>{t('這是描述性拍賣結果分布，並非競標人數或競爭強度的衡量。', 'A descriptive outcome distribution, not a measure of bidder count or competition.')}</p><ul>{bins.map((bin) => <li key={bin.label}>{bin.label}: {bin.count}</li>)}</ul></article><article><h4>{t('得標人彙整', 'Winning-bidder aggregation')}</h4><p>{t(`有效決標紀錄對應 ${bidderGroups.length} 個來源記載得標人；${repeatWins} 筆紀錄屬重複得標人。`, `${awardRows.length} valid awards correspond to ${bidderGroups.length} source-recorded bidder names; ${repeatWins} records are associated with repeat winners.`)}</p><small>{t('本頁不建立個人檔案、外部補充或投資人排行榜。', 'No profiles, external enrichment, or investor leaderboard is created.')}</small></article></div></section>
    <section className="chart-grid"><article className="chart-card"><h3>{t('決標價與總底價', 'Awarded price vs total reserve')}</h3><p className="muted">{t('衍生比較；斜線代表 1:1。', 'Derived comparison; the diagonal is 1:1.')}</p><ResponsiveContainer width="100%" height={270}><ScatterChart margin={{ top: 16, right: 18, bottom: 18, left: 18 }}><CartesianGrid /><XAxis dataKey="x" type="number" name={t('總底價', 'Total reserve')} tickFormatter={(value) => `${Math.round(value / 1_000_000)}M`} /><YAxis dataKey="y" type="number" name={t('決標價', 'Awarded price')} tickFormatter={(value) => `${Math.round(value / 1_000_000)}M`} /><Tooltip formatter={(value) => money(Number(value))} labelFormatter={() => ''} content={({ payload }) => { const row = payload?.[0]?.payload as RecordItem | undefined; return row ? <div className="chart-tooltip"><b>{row.districtName} · {row.landSection} · {row.parcelNumber}</b><br />{area(row.areaSqm)}<br />{t('總底價', 'Reserve')}: {money(row.totalReservePriceTwd)}<br />{t('決標價', 'Award')}: {money(row.awardedPriceTwd)}<br />{percent(row.premiumDiscountPct)}</div> : null; }} /><ReferenceLine segment={[{ x: 0, y: 0 }, { x: Math.max(...scatter.map((row) => row.x ?? 0), 1), y: Math.max(...scatter.map((row) => row.x ?? 0), 1) }]} stroke="#b45309" strokeDasharray="5 4" /><Scatter data={scatter} fill="#0f766e" /></ScatterChart></ResponsiveContainer></article><article className="chart-card"><h3>{t('溢價／折價分布', 'Premium / discount distribution')}</h3><ResponsiveContainer width="100%" height={270}><BarChart data={bins}><CartesianGrid vertical={false} /><XAxis dataKey="label" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="count" name={t('紀錄數', 'Records')} fill="#b45309" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></article><article className="chart-card"><h3>{t('行政區結果', 'District results')}</h3><p className="muted">{t('可切換檢視的圖表以紀錄數呈現；表格保留面積與決標額。', 'The chart shows record count; the table retains area and awarded amount.')}</p><ResponsiveContainer width="100%" height={270}><BarChart data={districtData}><CartesianGrid vertical={false} /><XAxis dataKey="name" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="records" name={t('紀錄數', 'Records')} fill="#155e75" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></article></section>
    <section className="analysis-list"><div className="section-heading"><div><p className="eyebrow">{t('行政區與段小段分析', 'DISTRICT & SECTION ANALYSIS')}</p><h3>{t('彙整只用於描述資料組合', 'Aggregates describe the record mix')}</h3></div></div><p className="notice">{t('行政區差異可能反映地號組合、權利範圍、地點、土地特性及案件數少等因素；不能據此判定最昂貴的不動產行政區。', 'District differences may reflect parcel mix, rights shares, location, land characteristics, and small case counts; they do not identify an “most expensive” real-estate district.')}</p><div className="table-wrap"><table><thead><tr><th>{t('行政區', 'District')}</th><th>{t('紀錄數', 'Records')}</th><th>{t('總面積', 'Total area')}</th><th>{t('決標金額合計', 'Total awarded')}</th><th>{t('決標單價中位數', 'Median award / m²')}</th></tr></thead><tbody>{districtData.map((row) => <tr key={row.name}><td>{row.name}</td><td>{row.records}</td><td>{area(row.area)}</td><td>{money(row.awarded)}</td><td>{money(row.medianAwardPerSqm)}</td></tr>)}</tbody></table></div><h4>{t('段小段摘要（至少 3 筆）', 'Land-section summary (minimum 3 records)')}</h4>{sectionData.length ? <div className="table-wrap"><table><thead><tr><th>{t('段小段', 'Section')}</th><th>{t('紀錄數', 'Records')}</th><th>{t('總面積', 'Total area')}</th><th>{t('面積中位數', 'Median area')}</th><th>{t('得標／底價中位數', 'Median award / reserve')}</th><th>{t('決標金額合計', 'Total awarded')}</th></tr></thead><tbody>{sectionData.map((row) => <tr key={row.name}><td>{row.name}</td><td>{row.records}</td><td>{area(row.totalArea)}</td><td>{area(row.medianArea)}</td><td>{row.medianRatio === null ? missing : row.medianRatio.toFixed(2)}</td><td>{money(row.awarded)}</td></tr>)}</tbody></table></div> : <p className="muted">{t('目前篩選結果沒有至少 3 筆的段小段可進行摘要。', 'No land section has the minimum three filtered records for an aggregate summary.')}</p>}</section>
    <section className="analysis-list"><div className="section-heading"><div><p className="eyebrow">{t('地號結果與來源資料表', 'PARCEL RESULTS & SOURCE TABLE')}</p><h3>{t('原始欄位保留並可展開查看', 'Preserved source fields with expandable details')}</h3></div><div><label className="checkbox-label"><input type="checkbox" checked={showDetails} onChange={(event) => setShowDetails(event.target.checked)} /> {t('顯示原登記名義人與得標人', 'Show holder and bidder')}</label><select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="lot">{t('依標號', 'Lot')}</option><option value="area">{t('依面積', 'Area')}</option><option value="reserve">{t('依總底價', 'Total reserve')}</option><option value="award">{t('依決標價', 'Awarded price')}</option><option value="premium">{t('依溢折價', 'Premium / discount')}</option></select></div></div><div className="table-wrap"><table><thead><tr><th>{t('標號', 'Lot')}</th><th>{t('行政區', 'District')}</th><th>{t('段小段', 'Section')}</th><th>{t('地號', 'Parcel')}</th><th>{t('面積', 'Area')}</th><th>{t('權利範圍', 'Rights')}</th><th>{t('標售底價', 'Reserve')}</th><th>{t('標售總底價', 'Total reserve')}</th><th>{t('決標金額', 'Awarded')}</th><th>{t('溢價／折價', 'Premium / discount')}</th><th>{t('決標單價／m²', 'Award / m²')}</th>{showDetails && <><th>{t('原登記名義人', 'Original holder')}</th><th>{t('得標人', 'Winning bidder')}</th></>}<th>{t('來源細節', 'Source')}</th></tr></thead><tbody>{visible.map((record) => <tr key={record.id}><td>{record.lotNumberRaw || missing}</td><td>{record.districtName || missing}</td><td>{record.landSection || missing}</td><td>{record.parcelNumber || missing} {record.parcelNumber && <button className="link-button" onClick={() => navigator.clipboard?.writeText(record.parcelNumber)}>{t('複製', 'Copy')}</button>}</td><td>{area(record.areaSqm)}</td><td>{record.rightsShareRaw || missing}</td><td>{money(record.reservePriceTwd)}</td><td>{money(record.totalReservePriceTwd)}</td><td>{money(record.awardedPriceTwd)}</td><td className={(record.premiumDiscountPct ?? 0) < 0 ? 'negative' : ''}>{percent(record.premiumDiscountPct)}</td><td>{money(record.awardedPricePerSqm)}</td>{showDetails && <><td>{record.originalRegisteredHolderRaw || missing}</td><td>{record.winningBidderRaw || missing}</td></>}<td><details><summary>{t('查看', 'View')}</summary><pre>{JSON.stringify({ source: record.sourceRaw, inheritedLocator: record.inheritedLocator, derived: { priceDifferenceTwd: record.priceDifferenceTwd, awardToReserveRatio: record.awardToReserveRatio, premiumDiscountPct: record.premiumDiscountPct, reservePricePerSqm: record.reservePricePerSqm, awardedPricePerSqm: record.awardedPricePerSqm } }, null, 2)}</pre></details></td></tr>)}</tbody></table></div><nav className="pagination"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>{t('上一頁', 'Previous')}</button><span>{t('第', 'Page ')} {page} / {pages}</span><button disabled={page === pages} onClick={() => setPage((value) => value + 1)}>{t('下一頁', 'Next')}</button></nav></section>
    <section className="analysis-list"><div className="section-heading"><div><p className="eyebrow">{t('資料品質與方法', 'DATA QUALITY & METHODS')}</p><h3>{t('不自動更正來源紀錄', 'Source records are never silently corrected')}</h3></div></div><ul>{quality.map(([label, count]) => <li key={label}>{label}: <b>{count}</b></li>)}</ul><p>{metadata.reservePriceFieldInterpretation ?? missing}</p><p>{t('衍生計算只在所需金額可解析時呈現：差額＝決標金額－標售總底價；得標／底價比＝決標金額÷標售總底價；溢折價＝（比率－1）×100；每平方公尺價格＝相關金額÷面積。這些是拍賣結果分析，不是市場價格、公告現值或估價。', 'Derived measures appear only when required amounts parse: difference = award − total reserve; award/reserve = award ÷ total reserve; premium/discount = (ratio − 1) × 100; price per m² = the relevant amount ÷ area. These are auction-outcome analytics, not market prices, announced land values, or appraisals.')}</p><p>{t('地籍清理拍賣、一般不動產交易、公告地價及徵收有不同法律背景與價格形成機制，不應視為等同市場指標。', 'Cadastral-cleanup auctions, ordinary real-estate transactions, announced land values, and land expropriation have different legal contexts and price-formation mechanisms and should not be treated as equivalent market indicators.')}</p><p><a href={metadata.sourceUrl} target="_blank" rel="noreferrer">{t('官方資料來源與更新資訊', 'Official source and update information')}</a> · {t('詮釋資料更新', 'Metadata updated')}: {metadata.metadataUpdatedAt ?? missing}</p></section>
  </>;
}
