import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './models';

type AuctionRecord = { id:string; lotNumberRaw:string; districtName:string; landSection:string; parcelNumber:string; areaSqmRaw:string; areaSqm:number|null; originalRegisteredHolderRaw:string; rightsShareRaw:string; rightsRatio:number|null; reservePriceRaw:string; reservePriceTwd:number|null; totalReservePriceRaw:string; totalReservePriceTwd:number|null; awardedPriceRaw:string; awardedPriceTwd:number|null; winningBidderRaw:string; premiumDiscountPct:number|null; awardToReserveRatio:number|null; awardedPricePerSqm:number|null; hasValidArea:boolean; hasValidReservePrice:boolean; hasValidAwardedPrice:boolean; sourceRaw:Record<string,string>; inheritedLocator:Record<string,string> };
type Metadata = { totalRecords?:number; resourceUpdatedAt?:string; metadataUpdatedAt?:string; ingestionTimestamp?:string; sourceUrl?:string; qualityCounts?:Record<string,number>; reservePriceFieldInterpretation?:string };

const base = import.meta.env.BASE_URL;
const MIN_VALID_AWARDS_FOR_COMPARISON = 5;
const missing = '—';
const sum = (values: Array<number | null>) => values.reduce<number>((total, value) => total + (value ?? 0), 0);
const median = (values: Array<number | null>) => { const valuesOnly = values.filter((value): value is number => value !== null && Number.isFinite(value)).sort((a, b) => a - b); const middle = Math.floor(valuesOnly.length / 2); return !valuesOnly.length ? null : valuesOnly.length % 2 ? valuesOnly[middle] : (valuesOnly[middle - 1] + valuesOnly[middle]) / 2; };
const csvCell = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;

export function CadastralCleanupLandAuctionResults({ language }: { language: Language }) {
  const t = (zh: string, en: string) => language === 'zh' ? zh : en;
  const [records, setRecords] = useState<AuctionRecord[]>([]); const [metadata, setMetadata] = useState<Metadata>({});
  const [district, setDistrict] = useState(''); const [section, setSection] = useState(''); const [query, setQuery] = useState(''); const [bidderQuery, setBidderQuery] = useState(''); const [rightsType, setRightsType] = useState(''); const [validAward, setValidAward] = useState('');
  const [revealNames, setRevealNames] = useState(false); const [page, setPage] = useState(1); const [sort, setSort] = useState<'lot'|'area'|'reserve'|'award'|'premium'>('lot');
  useEffect(() => { Promise.all([fetch(`${base}data/cadastral-cleanup-land-auction-results/records.json`).then((response) => response.json()), fetch(`${base}data/cadastral-cleanup-land-auction-results/metadata.json`).then((response) => response.json())]).then(([items, info]) => { setRecords(items); setMetadata(info); }).catch(() => setRecords([])); }, []);
  const districts = useMemo(() => [...new Set(records.map((record) => record.districtName).filter(Boolean))].sort(), [records]);
  const sections = useMemo(() => [...new Set(records.map((record) => record.landSection).filter(Boolean))].sort(), [records]);
  const filtered = useMemo(() => {
    const keyword = query.trim().toLowerCase(); const bidder = bidderQuery.trim().toLowerCase();
    return records.filter((record) => {
      const rightKind = record.rightsRatio === 1 ? 'full' : record.rightsRatio !== null ? 'fraction' : record.rightsShareRaw ? 'other' : 'missing';
      const searchable = [record.lotNumberRaw, record.districtName, record.landSection, record.parcelNumber, record.rightsShareRaw, ...(revealNames ? [record.originalRegisteredHolderRaw, record.winningBidderRaw] : [])].join(' ').toLowerCase();
      return (!district || record.districtName === district) && (!section || record.landSection === section) && (!keyword || searchable.includes(keyword)) && (!rightsType || rightKind === rightsType) && (!validAward || String(record.hasValidAwardedPrice) === validAward) && (!bidder || (revealNames && record.winningBidderRaw.toLowerCase().includes(bidder)));
    }).sort((a, b) => sort === 'lot' ? a.lotNumberRaw.localeCompare(b.lotNumberRaw, 'zh-Hant') : (b[sort === 'area' ? 'areaSqm' : sort === 'reserve' ? 'totalReservePriceTwd' : sort === 'award' ? 'awardedPriceTwd' : 'premiumDiscountPct'] ?? -Infinity) - (a[sort === 'area' ? 'areaSqm' : sort === 'reserve' ? 'totalReservePriceTwd' : sort === 'award' ? 'awardedPriceTwd' : 'premiumDiscountPct'] ?? -Infinity));
  }, [records, district, section, query, bidderQuery, rightsType, validAward, revealNames, sort]);
  useEffect(() => setPage(1), [district, section, query, bidderQuery, rightsType, validAward, revealNames, sort]);
  const money = (value: number | null) => value === null ? missing : `$${Math.round(value).toLocaleString('zh-TW')}`;
  const area = (value: number | null) => value === null ? missing : `${value.toLocaleString('zh-TW', { maximumFractionDigits: 2 })} m²`;
  const percent = (value: number | null) => value === null ? missing : `${value.toLocaleString('zh-TW', { maximumFractionDigits: 1, signDisplay: 'always' })}%`;
  const awardRows = filtered.filter((record) => record.hasValidAwardedPrice); const premiumRows = awardRows.filter((record) => record.premiumDiscountPct !== null); const sufficientAwards = awardRows.length >= MIN_VALID_AWARDS_FOR_COMPARISON;
  const above = premiumRows.filter((record) => (record.premiumDiscountPct ?? 0) > 0).length; const at = premiumRows.filter((record) => record.premiumDiscountPct === 0).length; const below = premiumRows.filter((record) => (record.premiumDiscountPct ?? 0) < 0).length;
  const kpis = [[t('標售結果紀錄', 'Auction-result records'), String(filtered.length)], [t('行政區', 'Districts'), String(new Set(filtered.map((record) => record.districtName)).size)], [t('段小段', 'Land sections'), String(new Set(filtered.map((record) => record.landSection)).size)], [t('來源記載面積合計', 'Source-recorded area'), area(sum(filtered.map((record) => record.areaSqm)))], [t('來源總底價合計', 'Source total reserve'), money(sum(filtered.map((record) => record.totalReservePriceTwd)))], [t('有效決標金額', 'Valid awards'), String(awardRows.length)], [t('決標金額中位數', 'Median awarded price'), sufficientAwards ? money(median(awardRows.map((record) => record.awardedPriceTwd))) : t('樣本不足', 'Insufficient sample')], [t('溢折價中位數', 'Median premium / discount'), sufficientAwards ? percent(median(premiumRows.map((record) => record.premiumDiscountPct))) : t('樣本不足', 'Insufficient sample')]];
  const scatter = awardRows.flatMap((record) => record.totalReservePriceTwd === null || record.awardedPriceTwd === null ? [] : [{ ...record, x: record.totalReservePriceTwd, y: record.awardedPriceTwd }]);
  const premiumBins = [-Infinity, 0, 10, 30, Infinity].map((upper, index, all) => ({ label: index === 0 ? '≤ 0%' : index === all.length - 1 ? '> 30%' : `${all[index - 1]}–${upper}%`, count: premiumRows.filter((record) => (record.premiumDiscountPct ?? 0) > (index ? all[index - 1] : -Infinity) && (record.premiumDiscountPct ?? 0) <= upper).length }));
  const districtRows = [...new Set(filtered.map((record) => record.districtName))].filter(Boolean).map((name) => { const items = filtered.filter((record) => record.districtName === name); const awards = items.filter((record) => record.hasValidAwardedPrice); return { name, records: items.length, area: sum(items.map((record) => record.areaSqm)), awarded: sum(awards.map((record) => record.awardedPriceTwd)), medianAwardPerSqm: awards.length >= MIN_VALID_AWARDS_FOR_COMPARISON ? median(awards.map((record) => record.awardedPricePerSqm)) : null }; });
  const qualityRows = [[t('缺少標號', 'Missing lot number'), filtered.filter((record) => !record.lotNumberRaw).length], [t('面積缺失或格式無效', 'Missing or malformed area'), filtered.filter((record) => !record.hasValidArea).length], [t('總底價缺失或格式無效', 'Missing or malformed total reserve'), filtered.filter((record) => !record.hasValidReservePrice).length], [t('決標金額無法解析', 'Unparseable awarded amount'), filtered.filter((record) => record.awardedPriceRaw && !record.hasValidAwardedPrice).length], [t('低於總底價（檢視旗標）', 'Below total reserve (review flag)'), below]];
  const pages = Math.max(1, Math.ceil(filtered.length / 15)); const visible = filtered.slice((page - 1) * 15, page * 15);
  const sourceForDisplay = (record: AuctionRecord) => revealNames ? record.sourceRaw : Object.fromEntries(Object.entries(record.sourceRaw).filter(([, value]) => value !== record.originalRegisteredHolderRaw && value !== record.winningBidderRaw));
  const exportCsv = () => { const header = ['Lot', 'District', 'Section', 'Parcel', 'Area m²', 'Rights share', 'Reserve price', 'Total reserve price', 'Awarded price', ...(revealNames ? ['Original registered holder', 'Winning bidder'] : [])]; const rows = filtered.map((record) => [record.lotNumberRaw, record.districtName, record.landSection, record.parcelNumber, record.areaSqmRaw, record.rightsShareRaw, record.reservePriceRaw, record.totalReservePriceRaw, record.awardedPriceRaw, ...(revealNames ? [record.originalRegisteredHolderRaw, record.winningBidderRaw] : [])]); const url = URL.createObjectURL(new Blob([[header, ...rows].map((row) => row.map(csvCell).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'cadastral-cleanup-land-auction-results-filtered.csv'; link.click(); URL.revokeObjectURL(url); };
  return <>
    <section className="section-intro"><p className="eyebrow">{t('地政／歷史行政紀錄', 'LAND ADMINISTRATION / HISTORICAL RECORDS')}</p><h2>{t('地籍清理公告開標結果土地清冊', 'Cadastral Cleanup Land Auction Results')}</h2><p>{t('本頁探索地籍清理程序下的來源記載標售結果，不是一般交易資料、現售標的、所有權查證或估價工具。', 'Explore source-recorded results from the cadastral-cleanup process. This is not an ordinary transaction database, a current listing, title verification, or valuation tool.')}</p><p className="notice">{t('資料未提供座標或界址；本模組不會地理編碼、繪製地圖或推定目前權利狀態。', 'The source provides no coordinates or geometry; this module does not geocode, map, or infer current rights.')}</p></section>
    <section className="analysis-list"><div className="section-heading"><div><p className="eyebrow">{t('篩選與隱私', 'FILTERS & PRIVACY')}</p><h3>{t('縮小分析範圍', 'Focus the analysis')}</h3></div><button className="link-button" onClick={exportCsv}>{t('下載篩選 CSV', 'Export filtered CSV')}</button></div><p className="notice">{t('原登記名義人與得標人是官方公開來源欄位。預設不顯示、搜尋或匯出；勾選後只供來源查核，不建立人物檔案、關係推論或排行。', 'Original-holder and winning-bidder names are official public-source fields. They are excluded from default display, search, and export; reveal them only for source verification, never for profiling, relationship inference, or rankings.')}</p><label className="checkbox-label"><input type="checkbox" checked={revealNames} onChange={(event) => setRevealNames(event.target.checked)} /> {t('顯示、搜尋與匯出官方人名欄位', 'Reveal, search, and export official name fields')}</label><div className="filter-grid"><label><span>{t('行政區', 'District')}</span><select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="">{t('全部', 'All')}</option>{districts.map((value) => <option key={value}>{value}</option>)}</select></label><label><span>{t('段小段', 'Land section')}</span><select value={section} onChange={(event) => setSection(event.target.value)}><option value="">{t('全部', 'All')}</option>{sections.map((value) => <option key={value}>{value}</option>)}</select></label><label className="search-field"><span>{t('關鍵字', 'Keyword')}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('行政區、段、地號、標號或權利範圍', 'District, section, parcel, lot, or rights share')} /></label><label><span>{t('權利範圍類型', 'Rights-share type')}</span><select value={rightsType} onChange={(event) => setRightsType(event.target.value)}><option value="">{t('全部', 'All')}</option><option value="full">{t('全部權利', 'Full')}</option><option value="fraction">{t('分數', 'Fraction')}</option><option value="other">{t('其他文字', 'Other text')}</option><option value="missing">{t('缺失', 'Missing')}</option></select></label>{revealNames && <label><span>{t('得標人精確搜尋', 'Winning bidder search')}</span><input value={bidderQuery} onChange={(event) => setBidderQuery(event.target.value)} /></label>}<label><span>{t('有有效決標金額', 'Valid awarded price')}</span><select value={validAward} onChange={(event) => setValidAward(event.target.value)}><option value="">{t('全部', 'All')}</option><option value="true">{t('是', 'Yes')}</option><option value="false">{t('否', 'No')}</option></select></label></div></section>
    <section><div className="section-heading"><div><p className="eyebrow">{t('拍賣概覽', 'AUCTION OVERVIEW')}</p><h3>{t('來源記載摘要', 'Source-recorded summary')}</h3></div><span className="muted">{t('來源更新', 'Source updated')}: {metadata.resourceUpdatedAt ?? missing}<br />{t('本機擷取', 'Local ingestion')}: {metadata.ingestionTimestamp ?? missing}</span></div><div className="metric-strip">{kpis.map(([label, value]) => <article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><p className="muted">{t('總額與中位數會排除缺失或無法解析的值。資料涵蓋與更新紀錄可在「資料狀態與更新期間」頁籤檢視。', 'Totals and medians exclude missing or unparseable values. Review coverage and update records in the Data Status & Coverage tab.')}</p></section>
    {!sufficientAwards ? <section className="analysis-list"><p className="notice">{t(`目前篩選結果只有 ${awardRows.length} 筆有效決標金額，低於比較分析所需的 ${MIN_VALID_AWARDS_FOR_COMPARISON} 筆門檻。為避免少數個案被誤讀為市場或行政區洞察，已停用溢折價、得標人與行政區的衍生比較圖表。`, `This filtered view has ${awardRows.length} valid awarded prices, below the ${MIN_VALID_AWARDS_FOR_COMPARISON}-record threshold for comparative analysis. Premium, bidder, and district-derived comparison charts are withheld to prevent a few cases from being mistaken for market or district insight.`)}</p></section> : <><section className="analysis-list"><div className="section-heading"><div><p className="eyebrow">{t('動態洞察', 'DYNAMIC INSIGHTS')}</p><h3>{t('目前篩選結果的描述性拍賣結果', 'Descriptive outcome for current filters')}</h3></div><span className="muted">n = {awardRows.length}</span></div><div className="insight-grid"><article><h4>{t('溢價／折價', 'Premium / discount')}</h4><p>{t(`中位數為 ${percent(median(premiumRows.map((record) => record.premiumDiscountPct)))}。`, `The median was ${percent(median(premiumRows.map((record) => record.premiumDiscountPct)))}.`)}</p><small>{t(`高於底價 ${above} 筆、等於 ${at} 筆、低於 ${below} 筆。`, `${above} above reserve, ${at} at reserve, ${below} below reserve.`)}</small></article><article><h4>{t('得標人彙整', 'Winning-bidder aggregation')}</h4><p>{t('僅描述來源記載結果，不建立人物檔案或投資人排行。', 'Describes source-recorded outcomes only; no profiles or bidder rankings are created.')}</p></article></div></section><section className="chart-grid"><article className="chart-card"><h3>{t('決標價與總底價', 'Awarded price vs total reserve')}</h3><p className="muted">n = {scatter.length} · {t('衍生比較；斜線代表 1:1。', 'Derived comparison; the diagonal is 1:1.')}</p><ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid /><XAxis dataKey="x" type="number" tickFormatter={(value) => `${Math.round(value / 1_000_000)}M`} /><YAxis dataKey="y" type="number" tickFormatter={(value) => `${Math.round(value / 1_000_000)}M`} /><Tooltip formatter={(value) => money(Number(value))} /><ReferenceLine segment={[{ x: 0, y: 0 }, { x: Math.max(...scatter.map((row) => row.x), 1), y: Math.max(...scatter.map((row) => row.x), 1) }]} stroke="#b45309" strokeDasharray="5 4" /><Scatter data={scatter} fill="#0f766e" /></ScatterChart></ResponsiveContainer></article><article className="chart-card"><h3>{t('溢價／折價分布', 'Premium / discount distribution')}</h3><p className="muted">n = {premiumRows.length}</p><ResponsiveContainer width="100%" height={260}><BarChart data={premiumBins}><CartesianGrid vertical={false} /><XAxis dataKey="label" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="count" fill="#b45309" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></article></section></>}
    <section className="analysis-list"><div className="section-heading"><div><p className="eyebrow">{t('行政區分析', 'DISTRICT ANALYSIS')}</p><h3>{t('彙整只描述資料組合', 'Aggregates describe the record mix')}</h3></div></div><p className="notice">{t('行政區差異可能反映地號組合、權利範圍、地點、土地特性與案件數少；不能據此判定最昂貴的不動產行政區。', 'District differences may reflect parcel mix, rights shares, location, land characteristics, and small case counts; they do not identify an “most expensive” real-estate district.')}</p><div className="table-wrap"><table><thead><tr><th>{t('行政區', 'District')}</th><th>{t('紀錄數', 'Records')}</th><th>{t('總面積', 'Total area')}</th><th>{t('有效決標額合計', 'Valid awarded total')}</th><th>{t('決標單價中位數', 'Median award / m²')}</th></tr></thead><tbody>{districtRows.map((row) => <tr key={row.name}><td>{row.name}</td><td>{row.records}</td><td>{area(row.area)}</td><td>{money(row.awarded)}</td><td>{sufficientAwards ? money(row.medianAwardPerSqm) : t('樣本不足', 'Insufficient sample')}</td></tr>)}</tbody></table></div></section>
    <section className="analysis-list"><div className="section-heading"><div><p className="eyebrow">{t('地號結果與來源資料表', 'PARCEL RESULTS & SOURCE TABLE')}</p><h3>{t('來源欄位保留、個人欄位須主動揭露', 'Source fields preserved; names require explicit reveal')}</h3></div><select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="lot">{t('依標號', 'Lot')}</option><option value="area">{t('依面積', 'Area')}</option><option value="reserve">{t('依總底價', 'Total reserve')}</option><option value="award">{t('依決標價', 'Awarded price')}</option><option value="premium">{t('依溢折價', 'Premium / discount')}</option></select></div><div className="table-wrap"><table><thead><tr><th>{t('標號', 'Lot')}</th><th>{t('行政區', 'District')}</th><th>{t('段小段', 'Section')}</th><th>{t('地號', 'Parcel')}</th><th>{t('面積', 'Area')}</th><th>{t('權利範圍', 'Rights')}</th><th>{t('標售總底價', 'Total reserve')}</th><th>{t('決標金額', 'Awarded')}</th><th>{t('溢價／折價', 'Premium / discount')}</th>{revealNames && <><th>{t('原登記名義人', 'Original holder')}</th><th>{t('得標人', 'Winning bidder')}</th></>}<th>{t('來源細節', 'Source')}</th></tr></thead><tbody>{visible.map((record) => <tr key={record.id}><td>{record.lotNumberRaw || missing}</td><td>{record.districtName || missing}</td><td>{record.landSection || missing}</td><td>{record.parcelNumber || missing} {record.parcelNumber && <button className="copy-button" onClick={() => navigator.clipboard?.writeText(record.parcelNumber)}>{t('複製', 'Copy')}</button>}</td><td>{area(record.areaSqm)}</td><td>{record.rightsShareRaw || missing}</td><td>{money(record.totalReservePriceTwd)}</td><td>{money(record.awardedPriceTwd)}</td><td>{percent(record.premiumDiscountPct)}</td>{revealNames && <><td>{record.originalRegisteredHolderRaw || missing}</td><td>{record.winningBidderRaw || missing}</td></>}<td><details><summary>{t('查看', 'View')}</summary><pre>{JSON.stringify({ source: sourceForDisplay(record), inheritedLocator: record.inheritedLocator, derived: { awardToReserveRatio: record.awardToReserveRatio, premiumDiscountPct: record.premiumDiscountPct, awardedPricePerSqm: record.awardedPricePerSqm } }, null, 2)}</pre></details></td></tr>)}</tbody></table></div><nav className="pagination"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>{t('上一頁', 'Previous')}</button><span>{t('第', 'Page ')} {page} / {pages}</span><button disabled={page === pages} onClick={() => setPage((value) => value + 1)}>{t('下一頁', 'Next')}</button></nav></section>
    <section className="analysis-list"><div className="section-heading"><div><p className="eyebrow">{t('資料品質與方法', 'DATA QUALITY & METHODS')}</p><h3>{t('不自動更正來源紀錄', 'Source records are never silently corrected')}</h3></div></div><ul>{qualityRows.map(([label, count]) => <li key={label}>{label}: <b>{count}</b></li>)}</ul><p>{t('來源每列均記載「標售底價金額」；「標售總底價金額」只出現在同一標售地號的首列。衍生比較只會在總底價存在且為正數時使用該欄位；後續列仍保留為獨立來源紀錄，不推定總底價。', metadata.reservePriceFieldInterpretation ?? missing)}</p><p>{t('衍生比較只在金額可解析且樣本達門檻時顯示；它們是拍賣結果分析，不是市場價格、公告現值或估價。', 'Derived comparisons appear only when amounts parse and the sample clears the threshold; they are auction-outcome analytics, not market prices, announced land values, or appraisals.')}</p><p><a href={metadata.sourceUrl} target="_blank" rel="noreferrer">{t('官方資料來源與更新資訊', 'Official source and update information')}</a> · {t('詮釋資料更新', 'Metadata updated')}: {metadata.metadataUpdatedAt ?? missing}</p></section>
  </>;
}
