import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './models';

type Record = { id: string; periodRaw: string; year: number | null; quarter: number | null; period: string | null; totalAmountNtd: number | null; category0Recipients: number | null; category0StandardNtd: number | null; category0AmountNtd: number | null; category1Recipients: number | null; category1StandardNtd: number | null; category1AmountNtd: number | null; category2HouseholdOccurrences: number | null; category2StandardNtd: number | null; category2AmountNtd: number | null };
type Summary = { recordCount: number; firstPeriod: string | null; latestPeriod: string | null; latest?: Record; dataQuality: { invalidPeriodCount: number; missingTotalAmountCount: number; duplicatePeriodCount: number } };
const base = import.meta.env.BASE_URL;
const money = (value: number | null | undefined, language: Language) => value == null ? '—' : `$${value.toLocaleString(language === 'zh' ? 'zh-TW' : 'en-US')}`;

export function LowIncomeHouseholdLivingAssistance({ language }: { language: Language }) {
  const label = (zh: string, en: string) => language === 'zh' ? zh : en;
  const [records, setRecords] = useState<Record[]>([]); const [summary, setSummary] = useState<Summary | null>(null); const [year, setYear] = useState('');
  useEffect(() => { Promise.all([fetch(`${base}data/low-income-household-living-assistance/records.json`).then((response) => response.json()), fetch(`${base}data/low-income-household-living-assistance/summary.json`).then((response) => response.json())]).then(([nextRecords, nextSummary]) => { setRecords(nextRecords); setSummary(nextSummary); }); }, []);
  const years = [...new Set(records.map((record) => record.year).filter((value): value is number => value !== null))].sort((a, b) => a - b);
  const filtered = useMemo(() => records.filter((record) => !year || record.year === Number(year)), [records, year]);
  const latest = summary?.latest;
  return <>
    <section className="section-intro"><h2>{label('低收入戶生活扶助', 'Low-Income Household Living Assistance')}</h2><p>{label('依臺北市政府社會局公開資料，檢視季度低收入戶生活扶助的總金額，以及第 0、1、2 類的來源欄位。', 'Explore quarterly low-income household living-assistance totals and source-reported fields for categories 0, 1, and 2 from Taipei City Department of Social Welfare open data.')}</p><p className="notice">{label('本頁為彙總行政統計，不用於判定個別家庭資格、給付金額或申請結果；請以主管機關的最新規定與審核為準。第 0、1 類為人次，第 2 類為戶次，不能相加或直接比較。', 'This page is aggregate administrative statistics, not an eligibility, payment, or application determination. Refer to the responsible authority’s current rules and review. Categories 0 and 1 are person-times; category 2 is household occurrences, so they are not additive or directly comparable.')}</p></section>
    <section className="metric-strip"><div><span>{label('最新季度', 'Latest quarter')}</span><strong>{latest?.period ?? '—'}</strong></div><div><span>{label('來源總金額', 'Source total amount')}</span><strong>{money(latest?.totalAmountNtd, language)}</strong></div><div><span>{label('第 0 類人次', 'Category 0 person-times')}</span><strong>{latest?.category0Recipients?.toLocaleString() ?? '—'}</strong></div><div><span>{label('第 1 類人次', 'Category 1 person-times')}</span><strong>{latest?.category1Recipients?.toLocaleString() ?? '—'}</strong></div><div><span>{label('第 2 類戶次', 'Category 2 household occurrences')}</span><strong>{latest?.category2HouseholdOccurrences?.toLocaleString() ?? '—'}</strong></div></section>
    <div className="chart-grid"><section className="chart-section"><h2>{label('季度來源總金額', 'Quarterly Source Total Amount')}</h2><ResponsiveContainer width="100%" height={300}><LineChart data={filtered}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="period" /><YAxis tickFormatter={(value) => `${Math.round(value / 1_000_000)}M`} /><Tooltip formatter={(value) => money(typeof value === 'number' ? value : null, language)} /><Line type="monotone" dataKey="totalAmountNtd" name={label('總金額', 'Source total amount')} stroke="#356f9d" strokeWidth={2} /></LineChart></ResponsiveContainer></section><section className="chart-section"><h2>{label('各類別來源金額', 'Source Amount by Category')}</h2><ResponsiveContainer width="100%" height={300}><BarChart data={filtered}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="period" /><YAxis tickFormatter={(value) => `${Math.round(value / 1_000_000)}M`} /><Tooltip formatter={(value) => money(typeof value === 'number' ? value : null, language)} /><Legend /><Bar dataKey="category0AmountNtd" name={label('第 0 類', 'Category 0')} stackId="amount" fill="#b24738" /><Bar dataKey="category1AmountNtd" name={label('第 1 類', 'Category 1')} stackId="amount" fill="#356f9d" /><Bar dataKey="category2AmountNtd" name={label('第 2 類', 'Category 2')} stackId="amount" fill="#737d68" /></BarChart></ResponsiveContainer></section></div>
    <section className="analysis-list"><h2>{label('季度來源資料表', 'Quarterly Source Table')}</h2><div className="filter-grid"><label><span>{label('年份', 'Year')}</span><select value={year} onChange={(event) => setYear(event.target.value)}><option value="">{label('全部年份', 'All years')}</option>{years.map((value) => <option key={value} value={value}>{value}</option>)}</select></label></div><p className="table-count">{filtered.length.toLocaleString()} {label('筆紀錄', 'records')}</p><div className="table-wrap"><table><thead><tr>{[label('季度', 'Quarter'), label('來源總金額', 'Source total amount'), label('第 0 類人次', 'Cat. 0 person-times'), label('第 0 類標準', 'Cat. 0 standard'), label('第 0 類金額', 'Cat. 0 amount'), label('第 1 類人次', 'Cat. 1 person-times'), label('第 1 類標準', 'Cat. 1 standard'), label('第 1 類金額', 'Cat. 1 amount'), label('第 2 類戶次', 'Cat. 2 household occurrences'), label('第 2 類標準', 'Cat. 2 standard'), label('第 2 類金額', 'Cat. 2 amount')].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{filtered.map((record) => <tr key={record.id}><th>{record.period}</th><td>{money(record.totalAmountNtd, language)}</td><td>{record.category0Recipients?.toLocaleString() ?? '—'}</td><td>{money(record.category0StandardNtd, language)}</td><td>{money(record.category0AmountNtd, language)}</td><td>{record.category1Recipients?.toLocaleString() ?? '—'}</td><td>{money(record.category1StandardNtd, language)}</td><td>{money(record.category1AmountNtd, language)}</td><td>{record.category2HouseholdOccurrences?.toLocaleString() ?? '—'}</td><td>{money(record.category2StandardNtd, language)}</td><td>{money(record.category2AmountNtd, language)}</td></tr>)}</tbody></table></div></section>
  </>;
}
