import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './models';

type Category = 'planning_approval' | 'construction_start' | 'construction_progress' | 'inspection_audit' | 'contract_procurement' | 'completion_opening' | 'land_development' | 'award_recognition' | 'official_visit' | 'environmental_safety' | 'administrative' | 'other';
type Milestone = { id:string; sourceYear:number; sourceResourceId:string; sourceSequenceNumber:string; cityCode:string; authorityCode:string; sourceDateRaw:string; month:number|null; date:string|null; datePrecision:'day'|'month'|'unknown'; milestoneDescription:string; originalDescriptionHeader:string; reportingUnitRaw:string; reportingUnits:string[]; detectedLines:string[]; detectedProjectNames:string[]; detectedContractCodes:string[]; milestoneCategory:Category; matchedCategoryTerms:string[]; hasValidDate:boolean; hasDetectedProject:boolean; sourceRaw:Record<string,string> };
type Metadata = { sourceRowCountByYear?:Record<string,number>; latestEventDate?:string; resourceIds?:Record<string,string> };
const base=import.meta.env.BASE_URL;
const labels:Record<Category,[string,string]>={planning_approval:['規劃與核定','Planning & approval'],construction_start:['開工','Construction start'],construction_progress:['施工進展','Construction progress'],inspection_audit:['查核與檢驗','Inspection & audit'],contract_procurement:['採購與契約','Contract & procurement'],completion_opening:['完工與啟用','Completion & opening'],land_development:['土地開發','Land development'],award_recognition:['獎項與表揚','Awards'],official_visit:['視察與參訪','Official visit'],environmental_safety:['環境與安全','Environment & safety'],administrative:['行政','Administrative'],other:['其他','Other']};
const csv=(x:unknown)=>`"${String(x??'').replaceAll('"','""')}"`;

export function MetroEngineeringMilestones({language}:{language:Language}){
 const l=(zh:string,en:string)=>language==='zh'?zh:en; const [rows,setRows]=useState<Milestone[]>([]);const [meta,setMeta]=useState<Metadata>({});const [year,setYear]=useState('');const [project,setProject]=useState('');const [unit,setUnit]=useState('');const [category,setCategory]=useState('');const [month,setMonth]=useState('');const [contract,setContract]=useState('');const [query,setQuery]=useState('');const [ascending,setAscending]=useState(false);const [page,setPage]=useState(1);
 useEffect(()=>{Promise.all([fetch(`${base}data/metro-engineering-milestones/records.json`).then(x=>x.json()),fetch(`${base}data/metro-engineering-milestones/metadata.json`).then(x=>x.json())]).then(([r,m])=>{setRows(r);setMeta(m)})},[]);
 const projects=[...new Set(rows.flatMap(r=>[...r.detectedLines,...r.detectedProjectNames]))].sort(),units=[...new Set(rows.flatMap(r=>r.reportingUnits))].sort(),years=[...new Set(rows.map(r=>r.sourceYear))].sort();
 const filtered=useMemo(()=>rows.filter(r=>(!year||String(r.sourceYear)===year)&&(!project||[...r.detectedLines,...r.detectedProjectNames].includes(project))&&(!unit||r.reportingUnits.includes(unit))&&(!category||r.milestoneCategory===category)&&(!month||String(r.month)===month)&&(!contract||r.detectedContractCodes.join(' ').toLowerCase().includes(contract.toLowerCase()))&&(!query||`${r.sourceSequenceNumber} ${r.sourceDateRaw} ${r.milestoneDescription}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>ascending?(a.date??'9999').localeCompare(b.date??'9999'):(b.date??'').localeCompare(a.date??'')),[rows,year,project,unit,category,month,contract,query,ascending]);
 const pages=Math.max(1,Math.ceil(filtered.length/15)),visible=filtered.slice((page-1)*15,page*15);const byYear=years.map(y=>({year:y,count:filtered.filter(r=>r.sourceYear===y).length}));const byCategory=(Object.keys(labels) as Category[]).map(c=>({name:l(...labels[c]),count:filtered.filter(r=>r.milestoneCategory===c).length})).filter(x=>x.count);const recordsWithContracts=filtered.filter(r=>r.detectedContractCodes.length).length;const copy=(text:string)=>navigator.clipboard?.writeText(text);
 const download=()=>{const h=['Year','Date','Milestone','Detected projects/lines','Category','Contract codes','Reporting unit','City code','Authority code','Resource'];const b=filtered.map(r=>[r.sourceYear,r.sourceDateRaw,r.milestoneDescription,[...r.detectedLines,...r.detectedProjectNames].join(' | '),r.milestoneCategory,r.detectedContractCodes.join(' | '),r.reportingUnitRaw,r.cityCode,r.authorityCode,r.sourceResourceId]);const u=URL.createObjectURL(new Blob([[h,...b].map(r=>r.map(csv).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='metro-engineering-milestones.csv';a.click();URL.revokeObjectURL(u)};
 return <><section className="section-intro"><h2>{l('臺北捷運工程大事紀要','Taipei Metro Engineering Milestones')}</h2><p className="notice">{l('這是 2024 與 2025 年度行政大事紀要，不是即時工程進度、完工預測、通車時程、預算或品質評估。文字偵測出的路線、專案、契約代碼與分類皆為衍生分析。','This is an annual administrative milestone archive for 2024 and 2025, not a live progress tracker, completion forecast, opening schedule, budget, or quality assessment. Detected lines, projects, contract codes, and categories are derived analysis.')}</p><p>{l('捷運工程事件提供都市發展脈絡；單一事件或提及次數不能直接證明房價、租金或交易量的變化。','Metro engineering milestones provide urban-development context, but a single project event or number of mentions does not directly establish changes in property prices, rents, or transaction volume.')}</p></section>
 <section className="metric-strip">{[[l('篩選後紀錄','Filtered records'),filtered.length],[l('涵蓋年度','Years covered'),years.length],[l('偵測路線/專案','Detected lines/projects'),new Set(filtered.flatMap(r=>[...r.detectedLines,...r.detectedProjectNames])).size],[l('提報單位','Reporting units'),new Set(filtered.flatMap(r=>r.reportingUnits)).size],[l('含契約代碼','With contract codes'),recordsWithContracts],[l('查核與檢驗','Inspection/audit'),filtered.filter(r=>r.milestoneCategory==='inspection_audit').length],[l('開工事件','Construction starts'),filtered.filter(r=>r.milestoneCategory==='construction_start').length],[l('最新紀要','Latest recorded milestone'),meta.latestEventDate??'—']].map(([n,v])=><article className="metric" key={String(n)}><span>{n}</span><strong>{v}</strong></article>)}</section>
 <section className="analysis-list"><h3>{l('時間軸篩選','Timeline filters')}</h3><div className="filter-grid"><label><span>{l('年度','Year')}</span><select value={year} onChange={e=>{setYear(e.target.value);setPage(1)}}><option value="">All</option>{years.map(x=><option key={x}>{x}</option>)}</select></label><label><span>{l('路線或專案（衍生）','Line/project (derived)')}</span><select value={project} onChange={e=>{setProject(e.target.value);setPage(1)}}><option value="">All</option>{projects.map(x=><option key={x}>{x}</option>)}</select></label><label><span>{l('分類（衍生）','Category (derived)')}</span><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">All</option>{(Object.keys(labels) as Category[]).map(x=><option key={x} value={x}>{l(...labels[x])}</option>)}</select></label><label><span>{l('提報單位','Reporting unit')}</span><select value={unit} onChange={e=>{setUnit(e.target.value);setPage(1)}}><option value="">All</option>{units.map(x=><option key={x}>{x}</option>)}</select></label><label><span>{l('月份','Month')}</span><select value={month} onChange={e=>{setMonth(e.target.value);setPage(1)}}><option value="">All</option>{Array.from({length:12},(_,i)=>i+1).map(x=><option key={x} value={x}>{x}</option>)}</select></label><label><span>{l('契約代碼搜尋','Contract-code search')}</span><input value={contract} onChange={e=>{setContract(e.target.value);setPage(1)}} placeholder="CQ860"/></label><label className="search-field"><span>{l('搜尋項次、原始日期或大事紀要','Search ID, raw date, or milestone')}</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label></div><button className="link-button" onClick={()=>setAscending(!ascending)}>{ascending?l('依日期新到舊','Newest first'):l('依日期舊到新','Oldest first')}</button><button className="link-button" onClick={download}>{l('下載篩選 CSV','Download filtered CSV')}</button></section>
 <section className="analysis-list"><h3>{l('客戶洞察與年度比較','Customer Insights and Year Comparison')}</h3><p>{l(`2024 與 2025 各有 ${meta.sourceRowCountByYear?.['2024']??'—'} 與 ${meta.sourceRowCountByYear?.['2025']??'—'} 筆大事紀要。兩年的發布量相同，差異較適合從專案組合、提報單位與事件分類理解，而非視為工程完成度。`,`2024 and 2025 each contain ${meta.sourceRowCountByYear?.['2024']??'—'} and ${meta.sourceRowCountByYear?.['2025']??'—'} milestone records. With equal published volume, differences are better understood through project mix, reporting units, and event categories—not completion progress.`)}</p><p>{l(`目前篩選中有 ${recordsWithContracts} 筆含保守偵測的契約代碼；重複出現只代表年度紀要中的文字提及，不表示延誤、成本或重要性。`,`The current selection has ${recordsWithContracts} records with conservatively detected contract codes. Repeated mentions represent annual-record text mentions only, not delay, cost, or importance.`)}</p><div className="chart-grid"><article className="chart-card"><h4>{l('各年度紀要筆數','Records by year')}</h4><ResponsiveContainer width="100%" height={230}><BarChart data={byYear}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="year"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#2563eb"/></BarChart></ResponsiveContainer></article><article className="chart-card"><h4>{l('里程碑分類','Milestone categories')}</h4><ResponsiveContainer width="100%" height={230}><BarChart data={byCategory} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={130}/><Tooltip/><Bar dataKey="count" fill="#7c3aed"/></BarChart></ResponsiveContainer></article></div></section>
 <section className="analysis-list"><h3>{l('工程大事時間軸與資料表','Timeline and Data Table')}</h3><div className="table-wrap"><table><thead><tr>{[l('年度','Year'),l('日期','Date'),l('大事紀要','Milestone'),l('偵測路線/專案','Detected project'),l('分類','Category'),l('契約','Contracts'),l('提報單位','Reporting unit'),l('來源','Source')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.sourceYear}</td><td>{(r.date??r.sourceDateRaw)||'—'}</td><td>{r.milestoneDescription}<button className="link-button" onClick={()=>copy(r.milestoneDescription)}>{l('複製','Copy')}</button></td><td>{[...r.detectedLines,...r.detectedProjectNames].join(' · ')||'—'}</td><td>{l(...labels[r.milestoneCategory])}</td><td>{r.detectedContractCodes.join(', ')||'—'}{r.detectedContractCodes.length>0&&<button className="link-button" onClick={()=>copy(r.detectedContractCodes.join(', '))}>{l('複製','Copy')}</button>}</td><td>{r.reportingUnitRaw||'—'}</td><td><details><summary>{l('檢視','View')}</summary><pre>{JSON.stringify({sourceResourceId:r.sourceResourceId,originalDescriptionHeader:r.originalDescriptionHeader,matchedCategoryTerms:r.matchedCategoryTerms,sourceRow:r.sourceRaw},null,2)}</pre></details></td></tr>)}</tbody></table></div><nav className="pagination"><button disabled={page===1} onClick={()=>setPage(x=>x-1)}>{l('上一頁','Previous')}</button><span>{page}/{pages}</span><button disabled={page===pages} onClick={()=>setPage(x=>x+1)}>{l('下一頁','Next')}</button></nav></section>
 <section className="analysis-list"><h3>{l('資料品質與方法','Data Quality and Methodology')}</h3><p>{l('日期僅解析明確的中文月日格式；僅有月份的紀錄保留月層級精度。專案、路線、分類與契約碼皆由可檢視的規則擷取，原始文字與年度來源仍保留。來源未提供座標、路線幾何或受影響行政區，因此不繪製地圖或推論地產影響。','Dates parse only clear Chinese month/day forms; month-only records retain month precision. Projects, lines, categories, and contract codes are extracted by inspectable rules while original text and year provenance are retained. The sources contain no coordinates, route geometry, or affected districts, so this module creates no maps or property-effect inferences.')}</p></section></>;
}
