import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './models';

type ParkingType = 'with_parking' | 'without_parking' | 'unknown';
type Record = { id:string; sequenceRaw:string; locationCode:string; address:string; buildingNumber:string; landDistrict:string; landSection:string; landParcel:string; houseLandShareRaw:string; parkingLandShareRaw:string; totalLandShareRaw:string; mainBuildingAreaSqm:number|null; balconyAreaSqm:number|null; awningAreaSqm:number|null; sourceTotalAreaSqm:number|null; commonAreaExcludingParkingSqm:number|null; propertyAreaSqm:number|null; propertyAreaPing:number|null; publicAreaRatio:number|null; reservePriceNtd:number|null; bidDepositNtd:number|null; reservePricePerPing:number|null; depositRatio:number|null; parkingDescription:string; normalizedParkingType:ParkingType; sourceRaw:{[key:string]:string} };
type Summary = { recordCount:number; validPriceAreaCount:number; locationCount:number; averageReservePriceNtd:number|null; medianReservePriceNtd:number|null; averagePropertyAreaPing:number|null; averageReservePricePerPing:number|null; medianPublicAreaRatio:number|null; minPublicAreaRatio:number; maxPublicAreaRatio:number; averageBidDepositNtd:number|null; medianBidDepositNtd:number|null; medianDepositRatio:number|null; byLocation:Array<{locationCode:string;recordCount:number;medianPropertyAreaPing:number|null;medianReservePriceNtd:number|null;medianReservePricePerPing:number|null;medianPublicAreaRatio:number|null}>; dataQuality:{[key:string]:number} };
const base=import.meta.env.BASE_URL;
const numbers=(values:Array<number|null>)=>values.filter((value):value is number=>value!==null).sort((a,b)=>a-b);
const median=(values:Array<number|null>)=>{const items=numbers(values);return !items.length?null:items.length%2?items[Math.floor(items.length/2)]:(items[items.length/2-1]+items[items.length/2])/2};
const money=(value:number|null|undefined,language:Language)=>value==null?'—':language==='zh'?`${Math.round(value/10_000).toLocaleString('zh-TW')} 萬元`:`NT$${(value/1_000_000).toLocaleString('en-US',{maximumFractionDigits:1})}M`;
const exactMoney=(value:number|null|undefined)=>value==null?'—':`NT$${Math.round(value).toLocaleString()}`;
const ping=(value:number|null|undefined)=>value==null?'—':`${value.toLocaleString(undefined,{maximumFractionDigits:2})} 坪`;
const percent=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?'—':`${value.toLocaleString(undefined,{maximumFractionDigits:2})}%`;
const parkingLabel=(type:ParkingType, language:Language)=>type==='with_parking'?(language==='zh'?'有車位':'With parking'):type==='without_parking'?(language==='zh'?'無車位':'Without parking'):(language==='zh'?'未明':'Unknown');
const bucket=(values:number[], cuts:number[], format:(value:number)=>string)=>cuts.map((cut,index)=>({label:index===0?`< ${format(cut)}`:index===cuts.length-1?`≥ ${format(cut)}`:`${format(cuts[index-1])}–${format(cut)}`,count:values.filter(value=>value>=(index?cuts[index-1]:-Infinity)&&value<(index===cuts.length-1?Infinity:cut)).length}));

export function MrtJointDevelopmentAuctionProperties({language}:{language:Language}) {
  const t=(zh:string,en:string)=>language==='zh'?zh:en; const [records,setRecords]=useState<Record[]>([]); const [summary,setSummary]=useState<Summary|null>(null); const [failed,setFailed]=useState(false); const [location,setLocation]=useState(''); const [search,setSearch]=useState(''); const [areaMin,setAreaMin]=useState(''); const [areaMax,setAreaMax]=useState(''); const [priceMin,setPriceMin]=useState(''); const [priceMax,setPriceMax]=useState(''); const [unitMin,setUnitMin]=useState(''); const [unitMax,setUnitMax]=useState(''); const [ratioMin,setRatioMin]=useState(''); const [ratioMax,setRatioMax]=useState(''); const [parking,setParking]=useState(''); const [sort,setSort]=useState('unit'); const [selected,setSelected]=useState<Record|null>(null);
  useEffect(()=>{Promise.all([fetch(`${base}data/mrt-joint-development-auction-properties/records.json`),fetch(`${base}data/mrt-joint-development-auction-properties/summary.json`)]).then(async([rows,info])=>{if(!rows.ok||!info.ok)throw Error();setRecords(await rows.json());setSummary(await info.json())}).catch(()=>setFailed(true))},[]);
  const locations=useMemo(()=>[...new Set(records.map(r=>r.locationCode).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-Hant')),[records]);
  const filtered=useMemo(()=>records.filter(r=>(!location||r.locationCode===location)&&(!parking||r.normalizedParkingType===parking)&&(!areaMin||(r.propertyAreaPing??-1)>=Number(areaMin))&&(!areaMax||(r.propertyAreaPing??Infinity)<=Number(areaMax))&&(!priceMin||(r.reservePriceNtd??-1)>=Number(priceMin)*10_000)&&(!priceMax||(r.reservePriceNtd??Infinity)<=Number(priceMax)*10_000)&&(!unitMin||(r.reservePricePerPing??-1)>=Number(unitMin)*10_000)&&(!unitMax||(r.reservePricePerPing??Infinity)<=Number(unitMax)*10_000)&&(!ratioMin||(r.publicAreaRatio??-1)>=Number(ratioMin))&&(!ratioMax||(r.publicAreaRatio??Infinity)<=Number(ratioMax))&&(!search||`${r.locationCode} ${r.address} ${r.buildingNumber} ${r.parkingDescription}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))),[records,location,parking,areaMin,areaMax,priceMin,priceMax,unitMin,unitMax,ratioMin,ratioMax,search]);
  const sorted=useMemo(()=>[...filtered].sort((a,b)=>sort==='price'?(b.reservePriceNtd??-1)-(a.reservePriceNtd??-1):sort==='area'?(b.propertyAreaPing??-1)-(a.propertyAreaPing??-1):sort==='public'?(b.publicAreaRatio??-1)-(a.publicAreaRatio??-1):sort==='deposit'?(b.bidDepositNtd??-1)-(a.bidDepositNtd??-1):(b.reservePricePerPing??-1)-(a.reservePricePerPing??-1)),[filtered,sort]);
  const prices=numbers(filtered.map(r=>r.reservePriceNtd)); const units=numbers(filtered.map(r=>r.reservePricePerPing)); const ratios=numbers(filtered.map(r=>r.publicAreaRatio)); const areas=numbers(filtered.map(r=>r.propertyAreaPing));
  const priceBands=bucket(prices,[10_000_000,20_000_000,30_000_000,50_000_000],v=>`${Math.round(v/10_000)}萬`); const unitBands=bucket(units,[500_000,800_000,1_100_000,1_500_000],v=>`${Math.round(v/10_000)}萬`); const ratioBands=bucket(ratios,[30,35,40,45],v=>`${v}%`); const sizeGroups=[{name:'<20',min:0,max:20},{name:'20–30',min:20,max:30},{name:'30–40',min:30,max:40},{name:'40–50',min:40,max:50},{name:'50–70',min:50,max:70},{name:'≥70',min:70,max:Infinity}].map(group=>{const rows=filtered.filter(r=>(r.propertyAreaPing??-1)>=group.min&&(r.propertyAreaPing??Infinity)<group.max);return {group:group.name,count:rows.length,medianPrice:median(rows.map(r=>r.reservePriceNtd)),medianUnit:median(rows.map(r=>r.reservePricePerPing))}});
  const parkingStats=(['with_parking','without_parking'] as ParkingType[]).map(type=>{const rows=filtered.filter(r=>r.normalizedParkingType===type);return {type:parkingLabel(type,language),count:rows.length,medianPrice:median(rows.map(r=>r.reservePriceNtd)),medianArea:median(rows.map(r=>r.propertyAreaPing)),medianUnit:median(rows.map(r=>r.reservePricePerPing))}});
  if(failed)return <p className="status">{t('資料載入失敗。','Unable to load MRT auction-property data.')}</p>;
  return <>
    <section className="section-intro"><h2>{t('捷運聯開標售','MRT Joint Development Auctions')}</h2><p>{t('依臺北捷運聯合開發公有不動產標售物件資料，比較標售底價、產權面積、公設比與押標金。','Compare reserve prices, property area, common-area ratio, and bid deposits in Taipei MRT joint-development public-property auction records.')}</p><p className="notice">{t('「底價單價」依標售底價與產權面積計算，並非實際成交單價；資料為歷史標售紀錄，不代表目前可標售物件、即時市價或投資價值。','“Reserve price per ping” is calculated from reserve price and property area; it is not an actual transaction price. These are historical auction records, not current listings, market value, or investment advice.')}</p><p className="muted">{t('資料來源：臺北市資料大平臺／臺北市政府捷運工程局；涵蓋 2016-04-26 至 2023-06-16，更新頻率：不定期。','Source: Taipei Open Data / Taipei Department of Rapid Transit Systems; coverage 2016-04-26 to 2023-06-16, updated irregularly.')} <a href="https://data.taipei/dataset/detail?id=9527ea34-7c55-4c23-9f0e-80164f888f06" target="_blank" rel="noreferrer">{t('官方資料集','Official dataset')}</a></p></section>
    <section className="metric-strip">{[[t('標售物件數','Auction properties'),filtered.length],[t('平均標售底價','Average reserve price'),money(prices.length?prices.reduce((a,b)=>a+b,0)/prices.length:null,language)],[t('標售底價中位數','Median reserve price'),money(median(prices),language)],[t('平均產權面積','Average property area'),ping(areas.length?areas.reduce((a,b)=>a+b,0)/areas.length:null)],[t('平均底價單價','Average reserve price per ping'),units.length?`${(units.reduce((a,b)=>a+b,0)/units.length/10_000).toFixed(1)} ${t('萬／坪','10k/ping')}`:'—'],[t('平均公設比','Average common-area ratio'),percent(ratios.length?ratios.reduce((a,b)=>a+b,0)/ratios.length:null)]].map(([name,value])=><article className="metric" key={String(name)}><span>{name}</span><strong>{value}</strong></article>)}</section>
    <section className="analysis-list"><h2>{t('物件篩選','Property filters')}</h2><details className="filters" open><summary>{t('篩選條件','Filters')}</summary><div className="filter-grid"><label><span>{t('區位','Development location')}</span><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">{t('全部','All')}</option>{locations.map(value=><option key={value}>{value}</option>)}</select></label><label><span>{t('車位','Parking')}</span><select value={parking} onChange={e=>setParking(e.target.value)}><option value="">{t('全部','All')}</option>{(['with_parking','without_parking','unknown'] as ParkingType[]).map(value=><option value={value} key={value}>{parkingLabel(value,language)}</option>)}</select></label><label><span>{t('坪數最低','Min. ping')}</span><input type="number" min="0" value={areaMin} onChange={e=>setAreaMin(e.target.value)}/></label><label><span>{t('坪數最高','Max. ping')}</span><input type="number" min="0" value={areaMax} onChange={e=>setAreaMax(e.target.value)}/></label><label><span>{t('底價最低（萬元）','Min. reserve (10k NTD)')}</span><input type="number" min="0" value={priceMin} onChange={e=>setPriceMin(e.target.value)}/></label><label><span>{t('底價最高（萬元）','Max. reserve (10k NTD)')}</span><input type="number" min="0" value={priceMax} onChange={e=>setPriceMax(e.target.value)}/></label><label><span>{t('單價最低（萬／坪）','Min. unit (10k/ping)')}</span><input type="number" min="0" value={unitMin} onChange={e=>setUnitMin(e.target.value)}/></label><label><span>{t('單價最高（萬／坪）','Max. unit (10k/ping)')}</span><input type="number" min="0" value={unitMax} onChange={e=>setUnitMax(e.target.value)}/></label><label><span>{t('公設比最低','Min. common ratio')}</span><input type="number" min="0" max="100" value={ratioMin} onChange={e=>setRatioMin(e.target.value)}/></label><label><span>{t('公設比最高','Max. common ratio')}</span><input type="number" min="0" max="100" value={ratioMax} onChange={e=>setRatioMax(e.target.value)}/></label><label><span>{t('排序','Sort')}</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="unit">{t('底價單價：高至低','Unit price: high to low')}</option><option value="price">{t('標售底價：高至低','Reserve price: high to low')}</option><option value="area">{t('產權面積：大至小','Area: large to small')}</option><option value="public">{t('公設比：高至低','Common ratio: high to low')}</option><option value="deposit">{t('押標金：高至低','Deposit: high to low')}</option></select></label><label className="search-field"><span>{t('搜尋','Search')}</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('區位、門牌、建號或車位','Location, address, building no., or parking')}/></label></div></details></section>
    <div className="chart-grid"><section className="chart-section"><h2>{t('標售價格分析','Reserve Price Analysis')}</h2><ResponsiveContainer width="100%" height={280}><BarChart data={priceBands}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#b24738" name={t('物件數','Properties')}/></BarChart></ResponsiveContainer></section><section className="chart-section"><h2>{t('底價單價分析','Reserve Price per Ping')}</h2><ResponsiveContainer width="100%" height={280}><BarChart data={unitBands}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#356f9d" name={t('物件數','Properties')}/></BarChart></ResponsiveContainer></section><section className="chart-section"><h2>{t('產權面積 vs 標售底價','Property Area vs Reserve Price')}</h2><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid/><XAxis type="number" dataKey="propertyAreaPing" name={t('產權坪數','Property area')} unit=" 坪"/><YAxis type="number" dataKey="reservePriceNtd" name={t('標售底價','Reserve price')} tickFormatter={v=>`${Math.round(v/1e6)}M`}/><Tooltip cursor={{strokeDasharray:'3 3'}} formatter={(v,name)=>name===t('標售底價','Reserve price')?exactMoney(Number(v)):v}/><Scatter data={filtered} fill="#c58a43"/></ScatterChart></ResponsiveContainer></section><section className="chart-section"><h2>{t('公設比分析','Common Area Ratio')}</h2><ResponsiveContainer width="100%" height={280}><BarChart data={ratioBands}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#737d68" name={t('物件數','Properties')}/></BarChart></ResponsiveContainer></section></div>
    <div className="chart-grid"><section className="analysis-list"><h2>{t('物件坪數分布','Property Size Distribution')}</h2><div className="table-wrap"><table><thead><tr><th>{t('坪數組距','Size band')}</th><th>{t('物件數','Count')}</th><th>{t('底價中位數','Median reserve')}</th><th>{t('底價單價中位數','Median unit')}</th></tr></thead><tbody>{sizeGroups.map(row=><tr key={row.group}><td>{row.group}</td><td>{row.count}</td><td>{money(row.medianPrice,language)}</td><td>{row.medianUnit==null?'—':`${(row.medianUnit/10_000).toFixed(1)} ${t('萬／坪','10k/ping')}`}</td></tr>)}</tbody></table></div></section><section className="analysis-list"><h2>{t('押標金與車位','Bid Deposit & Parking')}</h2><p>{t('押標金中位數','Median bid deposit')}: {money(median(filtered.map(r=>r.bidDepositNtd)),language)}；{t('押標金／底價中位數','Median deposit / reserve price')}: {percent(median(filtered.map(r=>r.depositRatio===null?null:r.depositRatio*100)))}</p><div className="table-wrap"><table><thead><tr><th>{t('車位類別','Parking')}</th><th>{t('物件數','Count')}</th><th>{t('底價中位數','Median reserve')}</th><th>{t('坪數中位數','Median area')}</th><th>{t('單價中位數','Median unit')}</th></tr></thead><tbody>{parkingStats.map(row=><tr key={row.type}><td>{row.type}</td><td>{row.count}</td><td>{money(row.medianPrice,language)}</td><td>{ping(row.medianArea)}</td><td>{row.medianUnit==null?'—':`${(row.medianUnit/10_000).toFixed(1)} ${t('萬／坪','10k/ping')}`}</td></tr>)}</tbody></table></div><p className="muted">{t('車位資訊僅依來源文字分類，不表示價格差異由車位造成。','Parking categories are based only on source text and do not establish a cause of price differences.')}</p></section></div>
    <section className="analysis-list"><h2>{t('各區位標售比較','Development Location Comparison')}</h2><div className="table-wrap"><table><thead><tr><th>{t('區位','Location')}</th><th>{t('物件數','Count')}</th><th>{t('坪數中位數','Median area')}</th><th>{t('底價中位數','Median reserve')}</th><th>{t('單價中位數','Median unit')}</th><th>{t('公設比中位數','Median common ratio')}</th></tr></thead><tbody>{(summary?.byLocation??[]).map(row=><tr key={row.locationCode}><td>{row.locationCode}</td><td>{row.recordCount}</td><td>{ping(row.medianPropertyAreaPing)}</td><td>{money(row.medianReservePriceNtd,language)}</td><td>{row.medianReservePricePerPing==null?'—':`${(row.medianReservePricePerPing/10_000).toFixed(1)} ${t('萬／坪','10k/ping')}`}</td><td>{percent(row.medianPublicAreaRatio)}</td></tr>)}</tbody></table></div></section>
    <section className="analysis-list"><h2>{t('物件明細','Property Directory')}</h2><p className="table-count">{sorted.length} {t('筆紀錄','records')} · {t('點選一列查看來源欄位與衍生指標。','Select a row to inspect source fields and derived metrics.')}</p><div className="table-wrap"><table><thead><tr>{[t('區位','Location'),t('門牌','Address'),t('產權面積','Property area'),t('主建物','Main building'),t('公設比','Common ratio'),t('標售底價','Reserve price'),t('底價單價','Reserve per ping'),t('押標金','Bid deposit'),t('車位','Parking')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{sorted.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td>{row.locationCode||'—'}</td><td>{row.address||'—'}</td><td>{ping(row.propertyAreaPing)}</td><td>{row.mainBuildingAreaSqm==null?'—':`${row.mainBuildingAreaSqm} ㎡`}</td><td>{percent(row.publicAreaRatio)}</td><td>{money(row.reservePriceNtd,language)}</td><td>{row.reservePricePerPing==null?'—':`${(row.reservePricePerPing/10_000).toFixed(1)} ${t('萬／坪','10k/ping')}`}</td><td>{money(row.bidDepositNtd,language)}</td><td>{row.parkingDescription||parkingLabel(row.normalizedParkingType,language)}</td></tr>)}</tbody></table></div></section>
    {selected&&<section className="analysis-list" aria-live="polite"><div className="section-heading"><h2>{t('物件詳細資料','Property Details')}</h2><button type="button" onClick={()=>setSelected(null)}>{t('關閉','Close')}</button></div><div className="detail-grid"><div><h3>{t('基本資料','Basic')}</h3><p>{t('區位代號','Location')}: {selected.locationCode||'—'}</p><p>{t('門牌','Address')}: {selected.address||'—'}</p><p>{t('建號','Building no.')}: {selected.buildingNumber||'—'}</p></div><div><h3>{t('面積','Area')}</h3><p>{t('主建物','Main building')}: {selected.mainBuildingAreaSqm??'—'} ㎡</p><p>{t('產權面積','Property area')}: {selected.propertyAreaSqm??'—'} ㎡ / {ping(selected.propertyAreaPing)}</p><p>{t('公設比','Common ratio')}: {percent(selected.publicAreaRatio)}</p></div><div><h3>{t('標售（含衍生）','Auction (including derived)')}</h3><p>{t('標售底價（來源）','Reserve price (source)')}: {exactMoney(selected.reservePriceNtd)}</p><p>{t('底價單價（衍生）','Reserve per ping (derived)')}: {selected.reservePricePerPing==null?'—':exactMoney(selected.reservePricePerPing)}</p><p>{t('押標金／底價（衍生）','Deposit / reserve (derived)')}: {percent(selected.depositRatio==null?null:selected.depositRatio*100)}</p></div><div><h3>{t('土地與車位','Land & Parking')}</h3><p>{t('土地座落','Land location')}: {[selected.landDistrict,selected.landSection,selected.landParcel].filter(Boolean).join(' ')||'—'}</p><p>{t('房屋土地持分','House land share')}: {selected.houseLandShareRaw||'—'}</p><p>{t('車位說明','Parking')}: {selected.parkingDescription||'—'}</p></div></div></section>}
  </>;
}
