import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './models';

type Status = 'completed' | 'construction' | 'design' | 'investment_or_preparation' | 'other';
type SiteRecord = { id:string; lineRaw:string; lineName:string; siteName:string; statusRaw:string; status:Status; remarks:string; sourceRaw:Record<string,string> };
type Summary = { recordCount:number; completedCount:number; constructionCount:number; designCount:number; investmentOrPreparationCount:number; activeCount:number; byStatus:Array<{statusRaw:string;status:Status;count:number;share:number}>; byLine:Array<{lineName:string;count:number;completedCount:number;constructionCount:number;designCount:number;investmentOrPreparationCount:number}>; mapAvailability:string };
type Metadata = { sourceUrl:string; sourceAgency:string; resourceUpdatedAt?:string; ingestionTimestamp?:string; importedRecordCount?:number };
const base = import.meta.env.BASE_URL;
const colors = ['#356f9d', '#c58a43', '#775f86', '#b24738', '#737d68'];
const statusLabel = (status:Status, language:Language) => ({ completed: language === 'zh' ? '已完工' : 'Completed', construction: language === 'zh' ? '施工中' : 'Under construction', design: language === 'zh' ? '規劃／設計中' : 'Planning / design', investment_or_preparation: language === 'zh' ? '招商／前置作業' : 'Investment / preparation', other: language === 'zh' ? '其他' : 'Other' })[status];
const percent = (value:number) => `${(value * 100).toLocaleString(undefined, { maximumFractionDigits: 1 })}%`;

export function MrtLandDevelopment({ language }:{ language:Language }) {
  const t = (zh:string, en:string) => language === 'zh' ? zh : en;
  const [records, setRecords] = useState<SiteRecord[]>([]); const [summary, setSummary] = useState<Summary|null>(null); const [metadata, setMetadata] = useState<Metadata|null>(null); const [failed, setFailed] = useState(false);
  const [line, setLine] = useState(''); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [sort, setSort] = useState<'line'|'site'|'status'>('line'); const [expanded, setExpanded] = useState<Set<string>>(new Set());
  useEffect(() => { Promise.all([fetch(`${base}data/mrt-land-development/records.json`), fetch(`${base}data/mrt-land-development/summary.json`), fetch(`${base}data/mrt-land-development/metadata.json`)]).then(async ([rows, info, meta]) => { if (!rows.ok || !info.ok || !meta.ok) throw Error(); setRecords(await rows.json()); setSummary(await info.json()); setMetadata(await meta.json()); }).catch(() => setFailed(true)); }, []);
  const lines = useMemo(() => [...new Set(records.map((record) => record.lineName))].sort((a,b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const statuses = useMemo(() => [...new Set(records.map((record) => record.statusRaw))], [records]);
  const filtered = useMemo(() => records.filter((record) => (!line || record.lineName === line) && (!status || record.statusRaw === status) && (!search || `${record.lineName} ${record.siteName} ${record.statusRaw} ${record.remarks}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))), [records, line, status, search]);
  const sorted = useMemo(() => [...filtered].sort((a,b) => (sort === 'site' ? a.siteName : sort === 'status' ? a.statusRaw : a.lineName).localeCompare(sort === 'site' ? b.siteName : sort === 'status' ? b.statusRaw : b.lineName, 'zh-Hant')), [filtered, sort]);
  const filteredStatus = useMemo(() => statuses.map((statusRaw) => { const rows = filtered.filter((record) => record.statusRaw === statusRaw); return { statusRaw, label: statusRaw, count: rows.length, share: filtered.length ? rows.length / filtered.length : 0 }; }).filter((item) => item.count), [filtered, statuses]);
  const filteredLines = useMemo(() => lines.map((lineName) => ({ lineName, count: filtered.filter((record) => record.lineName === lineName).length })).filter((item) => item.count).sort((a,b) => b.count - a.count || a.lineName.localeCompare(b.lineName, 'zh-Hant')), [filtered, lines]);
  const clear = () => { setLine(''); setStatus(''); setSearch(''); setSort('line'); };
  if (failed) return <p className="status">{t('資料載入失敗。', 'Unable to load MRT land-development data.')}</p>;
  return <>
    <section className="section-intro"><h2>{t('捷運土地開發', 'MRT Land Development')}</h2><p>{t('依捷運工程局公開資料，整理各捷運線土地開發基地的目前階段與案件分布。此處呈現的是資料更新時的狀態分布，不是個別基地的完整歷程。', 'Explore current-stage distribution and project counts for MRT land-development sites, based on the Department of Rapid Transit Systems public dataset. This is a current-status distribution, not complete project lifecycle history.')}</p><p className="notice">{t('資料未提供座標或地址，因此本模組不推定基地位置、不建立地圖標記，也不對房價、地價或租金提出因果解釋。', 'The source provides neither coordinates nor addresses. This module does not infer site locations or map markers, and makes no causal claims about property prices, land values, or rents.')}</p><p className="muted">{t('資料來源：臺北市資料大平臺／臺北市政府捷運工程局。', 'Source: Taipei Open Data / Taipei Department of Rapid Transit Systems.')} {metadata?.resourceUpdatedAt && `${t('資源更新：', 'Resource updated: ')}${metadata.resourceUpdatedAt}。`} {metadata?.ingestionTimestamp && `${t('本機匯入：', 'Local refresh: ')}${new Date(metadata.ingestionTimestamp).toLocaleString(language === 'zh' ? 'zh-TW' : 'en-US')}。`} <a href={metadata?.sourceUrl} target="_blank" rel="noreferrer">{t('官方資料集', 'Official dataset')}</a></p></section>
    <section className="metric-strip">{[[t('土地開發基地總數', 'Total development sites'), filtered.length], [t('已完工', 'Completed'), filtered.filter((r) => r.status === 'completed').length], [t('施工中', 'Under construction'), filtered.filter((r) => r.status === 'construction').length], [t('規劃／設計中', 'Planning / design'), filtered.filter((r) => r.status === 'design').length], [t('招商／前置作業', 'Investment / preparation'), filtered.filter((r) => r.status === 'investment_or_preparation').length]].map(([name, value]) => <article className="metric" key={String(name)}><span>{name}</span><strong>{value}</strong></article>)}</section>
    <details className="filters" open><summary>{t('篩選與排序', 'Filters and sorting')}</summary><div className="filter-grid"><label>{t('捷運線', 'MRT line')}<select value={line} onChange={(event) => setLine(event.target.value)}><option value="">{t('全部', 'All')}</option>{lines.map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('開發狀態', 'Development status')}<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{t('全部', 'All')}</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('排序', 'Sort')}<select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="line">{t('捷運線', 'MRT line')}</option><option value="site">{t('基地名稱', 'Site name')}</option><option value="status">{t('基地狀況', 'Development status')}</option></select></label><label className="search-field">{t('關鍵字', 'Keyword')}<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('搜尋線別、基地、狀態或備註', 'Search line, site, status, or remarks')} /></label></div><button className="link-button" type="button" onClick={clear}>{t('清除篩選', 'Clear filters')}</button></details>
    <section className="chart-grid"><article className="chart-section"><h2>{t('捷運土地開發基地狀況', 'MRT land-development site status')}</h2><div className="chart-frame"><ResponsiveContainer width="100%" height={Math.max(250, filteredStatus.length * 58)}><BarChart data={filteredStatus} layout="vertical" margin={{ left: 16, right: 42 }}><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" allowDecimals={false} /><YAxis type="category" dataKey="label" width={130} tick={{ fontSize: 12 }} /><Tooltip formatter={(value, _name, item) => [`${value} ${t('個基地', 'sites')} — ${percent((item.payload as {share:number}).share)}`, t('基地數', 'Sites')]} /><Bar dataKey="count" fill="#356f9d" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div></article><article className="chart-section"><h2>{t('各捷運線土地開發案件', 'Land-development sites by MRT line')}</h2><div className="chart-frame"><ResponsiveContainer width="100%" height={Math.max(250, filteredLines.length * 38)}><BarChart data={filteredLines} layout="vertical" margin={{ left: 16, right: 26 }}><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" allowDecimals={false} /><YAxis type="category" dataKey="lineName" width={120} tick={{ fontSize: 12 }} /><Tooltip /><Bar dataKey="count" fill="#b24738" radius={[0, 4, 4, 0]} onClick={(item) => { const payload = (item as unknown as {payload?: {lineName:string}}).payload; if (payload) setLine(payload.lineName); }} /></BarChart></ResponsiveContainer></div><p className="muted">{t('點選長條可篩選該捷運線。', 'Select a bar to filter this module to that MRT line.')}</p></article></section>
    <section className="chart-section"><h2>{t('捷運土地開發 Pipeline', 'MRT land-development pipeline')}</h2><p className="muted">{t('目前狀態分布，不表示同一基地的歷史推進順序。', 'Distribution of current statuses; it does not represent the historical progression of individual sites.')}</p><div className="pipeline">{(['investment_or_preparation', 'design', 'construction', 'completed'] as Status[]).map((item, index) => <div className="pipeline-step" key={item}><span>{statusLabel(item, language)}</span><strong>{filtered.filter((record) => record.status === item).length}</strong>{index < 3 && <i aria-hidden="true">→</i>}</div>)}</div></section>
    <section className="analysis-list"><h2>{t('資料洞察', 'Insights')}</h2><div className="insight-grid">{summary && <><article><h4>{t('開發進度', 'Development progress')}</h4><p>{t(`目前共有 ${summary.recordCount} 個捷運土地開發基地，其中 ${summary.completedCount} 個已完工，占全部基地 ${percent(summary.recordCount ? summary.completedCount / summary.recordCount : 0)}。`, `${summary.recordCount} MRT land-development sites are listed; ${summary.completedCount} are completed (${percent(summary.recordCount ? summary.completedCount / summary.recordCount : 0)}).`)}</p></article><article><h4>{t('開發中的案件', 'Active projects')}</h4><p>{t(`目前仍有 ${summary.activeCount} 個基地處於施工、設計、招商或前置作業階段。`, `${summary.activeCount} sites remain in construction, design, investment, or preliminary stages.`)}</p></article>{summary.byLine[0] && <article><h4>{t('捷運線集中度', 'Line concentration')}</h4><p>{t(`${summary.byLine[0].lineName}共有 ${summary.byLine[0].count} 個土地開發基地，是目前資料中案件最多的捷運線。`, `${summary.byLine[0].lineName} has ${summary.byLine[0].count} land-development sites, the largest count in this dataset.`)}</p></article>}</>}</div></section>
    <section className="chart-section"><h2>{t('基地明細', 'Site details')}</h2><p className="table-count">{t(`顯示 ${sorted.length} 個基地`, `Showing ${sorted.length} sites`)}</p><div className="table-wrap"><table><thead><tr><th>{t('線別', 'MRT line')}</th><th>{t('基地名稱', 'Site name')}</th><th>{t('基地狀況', 'Status')}</th><th>{t('備註', 'Remarks')}</th></tr></thead><tbody>{sorted.map((record) => { const open = expanded.has(record.id); const long = record.remarks.length > 80; return <tr key={record.id}><td>{record.lineName}</td><td>{record.siteName}</td><td>{record.statusRaw}</td><td>{long && !open ? `${record.remarks.slice(0, 80)}…` : record.remarks || '—'} {long && <button className="link-button" type="button" onClick={() => setExpanded((prior) => { const next = new Set(prior); if (next.has(record.id)) next.delete(record.id); else next.add(record.id); return next; })}>{open ? t('收合', 'Show less') : t('展開', 'Show more')}</button>}</td></tr>; })}</tbody></table></div></section>
  </>;
}
