import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './models'; import { qualityLabel } from './quality';

type Record = { id:string; rocYearRaw:string; gregorianYear:number|null; monthRaw:string; propertyNatureRaw:string; itemRaw:string; amountRaw:string; amountTwd:number|null; hasValidAmount:boolean; sourceRaw:globalThis.Record<string,string> };
type Summary = { propertyNatures:string[]; items:string[]; dataQuality:globalThis.Record<string,number>; aggregation:{officialTotalRowsDetected:boolean;totalRowLabels:string[]} };
const base=import.meta.env.BASE_URL;
const money=(value:number|undefined|null)=>value==null?'—':`$${value.toLocaleString('zh-TW',{maximumFractionDigits:2})}`;
const tooltipMoney=(value:unknown)=>money(typeof value==='number'?value:undefined);

export function MunicipalPropertyPortfolio({ language }: { language: Language }) {
  const l=(zh:string,en:string)=>language==='zh'?zh:en;
  const [records,setRecords]=useState<Record[]>([]); const [summary,setSummary]=useState<Summary|null>(null);
  const [year,setYear]=useState(''); const [nature,setNature]=useState(''); const [item,setItem]=useState(''); const [query,setQuery]=useState(''); const [page,setPage]=useState(1);
  useEffect(()=>{Promise.all([fetch(`${base}data/municipal-property-portfolio/records.json`).then(r=>r.json()),fetch(`${base}data/municipal-property-portfolio/summary.json`).then(r=>r.json())]).then(([r,s])=>{setRecords(r);setSummary(s)});},[]);
  const years=[...new Set(records.map(r=>r.gregorianYear).filter((v):v is number=>v!==null))].sort((a,b)=>a-b);
  const filtered=useMemo(()=>records.filter(r=>(!year||r.gregorianYear===Number(year))&&(!nature||r.propertyNatureRaw===nature)&&(!item||r.itemRaw===item)&&(!query||`${r.propertyNatureRaw} ${r.itemRaw} ${r.rocYearRaw} ${r.amountRaw}`.toLowerCase().includes(query.toLowerCase()))),[records,year,nature,item,query]);
  const total=(items:Record[])=>items.reduce((sum,r)=>sum+(r.amountTwd??0),0); const valid=filtered.filter(r=>r.hasValidAmount); const filteredTotal=total(valid);
  const byYear=years.map(year=>({year,amountTwd:total(records.filter(r=>r.gregorianYear===year&&r.hasValidAmount))})); const latest=byYear.at(-1),previous=byYear.at(-2);
  const natureData=[...new Set(valid.map(r=>r.propertyNatureRaw))].map(name=>({name,amountTwd:total(valid.filter(r=>r.propertyNatureRaw===name))})).sort((a,b)=>b.amountTwd-a.amountTwd);
  const pages=Math.max(1,Math.ceil(filtered.length/20)); const visible=filtered.slice((page-1)*20,page*20);
  const exportCsv=()=>{const rows=[['Year','Month','Property nature','Item','Amount (source)','Amount (TWD)'],...filtered.map(r=>[r.rocYearRaw,r.monthRaw,r.propertyNatureRaw,r.itemRaw,r.amountRaw,r.amountTwd??''])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}));a.download='municipal-property-portfolio-filtered.csv';a.click();};
  return <>
    <section className="section-intro"><h2>{l('臺北市市有財產總目錄','Taipei Municipal Property Portfolio')}</h2><p>{l('本模組以五年期市有財產總目錄的行政／會計金額，呈現財產性質別與項目結構。','This module presents five-year municipal property inventory amounts by property nature and item.')}</p><p className="notice">{l('來源金額是市有財產的行政或會計統計，並非市場價格、成交價格、可出售價值、投資報酬或政府財務績效。','Source amounts are administrative or accounting statistics, not market prices, transaction prices, realizable sale values, investment returns, or government financial performance.')}</p></section>
    <section className="analysis-list"><h2>{l('篩選條件','Filters')}</h2><div className="filter-grid"><label><span>{l('西元年','Gregorian year')}</span><select value={year} onChange={e=>{setYear(e.target.value);setPage(1)}}><option value="">{l('全部','All')}</option>{years.map(v=><option key={v}>{v}</option>)}</select></label><label><span>{l('財產性質別','Property nature')}</span><select value={nature} onChange={e=>{setNature(e.target.value);setPage(1)}}><option value="">{l('全部','All')}</option>{summary?.propertyNatures.map(v=><option key={v}>{v}</option>)}</select></label><label><span>{l('項目','Item')}</span><select value={item} onChange={e=>{setItem(e.target.value);setPage(1)}}><option value="">{l('全部','All')}</option>{summary?.items.map(v=><option key={v}>{v}</option>)}</select></label><label className="search-field"><span>{l('搜尋','Search')}</span><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={l('搜尋類別、項目、年度或來源金額','Search category, item, year, or source amount')}/></label></div></section>
    <section className="metric-strip">{[[l('目前篩選金額','Filtered amount'),money(filteredTotal)],[l('最新年度總額','Latest-year total'),money(latest?.amountTwd)],[l('前一年總額','Previous-year total'),money(previous?.amountTwd)],[l('年度變動','Year-over-year change'),latest&&previous?money(latest.amountTwd-previous.amountTwd):'—'],[l('財產性質別','Property natures'),natureData.length],[l('項目','Items'),new Set(valid.map(r=>r.itemRaw)).size]].map(([name,value])=><article className="metric" key={String(name)}><span>{name}</span><strong>{value}</strong></article>)}</section>
    <section className="chart-grid"><article className="chart-section"><h2>{l('總額年度趨勢','Total Portfolio Trend')}</h2><ResponsiveContainer width="100%" height={280}><LineChart data={byYear}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis tickFormatter={v=>`${Math.round(v/1e9)}B`}/><Tooltip formatter={tooltipMoney}/><Line dataKey="amountTwd" stroke="#356f9d" strokeWidth={3}/></LineChart></ResponsiveContainer></article><article className="chart-section"><h2>{l('財產性質別組成','Property Nature Composition')}</h2><ResponsiveContainer width="100%" height={280}><BarChart data={natureData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" angle={-25} textAnchor="end" height={75}/><YAxis tickFormatter={v=>`${Math.round(v/1e9)}B`}/><Tooltip formatter={tooltipMoney}/><Bar dataKey="amountTwd" fill="#737d68"/></BarChart></ResponsiveContainer></article></section>
    <section className="analysis-list"><h2>{l('資料洞察','Insights')}</h2><p>{latest?l(`最新年度 ${latest.year} 的來源列加總金額為 ${money(latest.amountTwd)}。`,`The sum of additive source rows in the latest year, ${latest.year}, is ${money(latest.amountTwd)}.`):'—'}</p><p>{natureData[0]?l(`目前篩選中金額最高的財產性質別為「${natureData[0].name}」，占有效篩選金額 ${filteredTotal?((natureData[0].amountTwd/filteredTotal)*100).toFixed(1):'0'}%。此占比不代表重要性或投資表現。`,`The largest property nature in the filtered data is “${natureData[0].name}”, representing ${filteredTotal?((natureData[0].amountTwd/filteredTotal)*100).toFixed(1):'0'}% of valid filtered amount. This share does not indicate importance or investment performance.`):'—'}</p></section>
    <section className="analysis-list"><h2>{l('資料表','Data Table')}</h2><button className="link-button" onClick={exportCsv}>{l('下載篩選 CSV','Download filtered CSV')}</button><div className="table-wrap"><table><thead><tr>{[l('年度','Year'),l('月份','Month'),l('財產性質別','Property nature'),l('項目','Item'),l('來源金額','Source amount'),l('資料品質','Data quality'),l('來源詳情','Source details')].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.rocYearRaw||'—'}{r.gregorianYear?` (${r.gregorianYear})`:''}</td><td>{r.monthRaw||'—'}</td><td>{r.propertyNatureRaw||'—'}</td><td>{r.itemRaw||'—'}</td><td title={r.amountRaw}>{money(r.amountTwd)}</td><td>{r.hasValidAmount?l('有效金額','Valid amount'):l('缺漏／未解析','Missing / unparseable')}</td><td><details><summary>{l('查看','View')}</summary><pre>{JSON.stringify(r.sourceRaw,null,2)}</pre></details></td></tr>)}</tbody></table></div><nav className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>{l('上一頁','Previous')}</button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>{l('下一頁','Next')}</button></nav></section>
    {summary&&<><section className="analysis-list"><h2>{l('資料品質','Data Quality')}</h2><p>{Object.entries(summary.dataQuality).map(([key,value])=>`${qualityLabel(key,language)}：${value}`).join('；')}</p><p>{summary.aggregation.officialTotalRowsDetected?l(`偵測到總計／小計列：${summary.aggregation.totalRowLabels.join('、')}；已從加總中排除。`,`Detected total/subtotal rows (${summary.aggregation.totalRowLabels.join(', ')}); they are excluded from sums.`):l('未偵測到總計或小計列；資料包含四種財產性質別與六種項目的互斥明細列，總額僅加總有效明細列。','No total or subtotal rows were detected. The data contains mutually exclusive detail rows for four property natures and six items; totals sum valid detail rows only.')}</p></section><section className="analysis-list"><h2>{l('資料說明','Data Notes')}</h2><p>{l('資料來源：臺北市政府財政局「近5年臺北市市有財產總目錄」，收錄期間為 2021-01-01 至 2025-12-31，每年更新。年增減可能反映取得、處分、重分類、會計處理或其他行政因素，不應直接解讀為市場升貶。','Source: Taipei Department of Finance, “Taipei Municipal Property Inventory for the Past Five Years,” covering 2021-01-01 through 2025-12-31 and updated annually. Annual changes may reflect acquisition, disposal, reclassification, accounting treatment, or other administrative factors and must not be read directly as market appreciation or depreciation.')}</p><p>{l('市有財產清冊是政府資產的行政與會計紀錄，與成交價格、住宅價格指數、公告土地現值和市場估價的定義及用途不同。','The municipal property inventory is an administrative and accounting record of government-owned assets. It differs in definition and purpose from actual transaction prices, residential price indices, announced land values, and market valuations.')}</p></section></>}
  </>;
}
