import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './models';

type Record = { id:string; sourceSequenceNumber:string; title:string; rocDateRaw:string; gregorianDate:string|null; gregorianYear:number|null; articleTypeRaw:string; articleType:string; countyCodeRaw:string; countyCode:string; hasValidDate:boolean; sourceRaw:globalThis.Record<string,string> };
type Summary = { totalRecords:number; uniqueTitles:number; validDateCount:number; invalidDateCount:number; earliestGregorianDate:string|null; latestGregorianDate:string|null; byArticleType:Array<{value:string;count:number}>; byGregorianYear:Array<{value:string;count:number}>; dataQuality:{missingTitleCount:number;missingSequenceNumberCount:number;duplicateSequenceNumberCount:number;exactDuplicateRowCount:number;duplicateTitleCount:number;missingArticleTypeCount:number;missingCountyCodeCount:number;countyCodeValues:string[];additionalFields:string[]} };
const base = import.meta.env.BASE_URL;
const csv = (v:string) => `"${v.replace(/"/g, '""')}"`;

export function UrbanRenewalRegulations({ language }: { language: Language }) {
  const l=(zh:string,en:string)=>language==='zh'?zh:en; const [records,setRecords]=useState<Record[]>([]); const [summary,setSummary]=useState<Summary|null>(null);
  const [query,setQuery]=useState(''); const [type,setType]=useState(''); const [yearFrom,setYearFrom]=useState(''); const [yearTo,setYearTo]=useState(''); const [dated,setDated]=useState(''); const [page,setPage]=useState(1);
  useEffect(()=>{Promise.all([fetch(`${base}data/urban-renewal-regulations/records.json`).then(x=>x.json()),fetch(`${base}data/urban-renewal-regulations/summary.json`).then(x=>x.json())]).then(([r,s])=>{setRecords(r);setSummary(s)});},[]);
  const types=[...new Set(records.map(r=>r.articleType).filter(Boolean))].sort();
  const filtered=useMemo(()=>records.filter(r=>{const q=query.trim().toLowerCase(); return (!type||r.articleType===type)&&(!yearFrom||(r.gregorianYear??0)>=Number(yearFrom))&&(!yearTo||(r.gregorianYear??Infinity)<=Number(yearTo))&&(!dated||(dated==='valid'?r.hasValidDate:!r.hasValidDate))&&(!q||`${r.title} ${r.articleTypeRaw} ${r.rocDateRaw} ${r.gregorianDate??''} ${r.countyCodeRaw} ${r.sourceSequenceNumber}`.toLowerCase().includes(q));}),[records,query,type,yearFrom,yearTo,dated]);
  const pages=Math.max(1,Math.ceil(filtered.length/15)); const visible=filtered.slice((page-1)*15,page*15); const activeTypes=[...new Map(filtered.map(r=>[r.articleType,0])).keys()].map(value=>({value,count:filtered.filter(r=>r.articleType===value).length})).sort((a,b)=>b.count-a.count);
  const years=[...new Map(filtered.filter(r=>r.gregorianYear).map(r=>[String(r.gregorianYear),0])).keys()].map(value=>({value,count:filtered.filter(r=>String(r.gregorianYear)===value).length})).sort((a,b)=>a.value.localeCompare(b.value));
  const exportCsv=()=>{const rows=[['ID','Title','Regulation type','ROC date','Gregorian date (derived)','CountyCode','Data status'],...filtered.map(r=>[r.sourceSequenceNumber,r.title,r.articleTypeRaw,r.rocDateRaw,r.gregorianDate??'',r.countyCodeRaw,r.hasValidDate?'valid date':'unparseable date'])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(row=>row.map(csv).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}));a.download='urban-renewal-regulations-filtered.csv';a.click();};
  const latest=filtered.filter(r=>r.gregorianDate).sort((a,b)=>(b.gregorianDate??'').localeCompare(a.gregorianDate??''))[0];
  return <>
    <section className="section-intro"><h2>{l('都市更新相關法規','Urban Renewal Regulations')}</h2><p>{l('以官方公開資料的標題、紀錄日期、類型與行政代碼進行查找；西元日期為由民國日期保守換算的衍生欄位。','Find official source records by title, record date, type, and administrative code. Gregorian dates are conservatively derived from ROC dates.')}</p><p className="notice">{l('本資料僅供參考，不表示法規現行有效、適用於特定更新案，亦不構成都市更新、土地、建築或其他法律意見。','This is a reference dataset. It does not establish current legal validity, applicability to a particular renewal project, or legal advice about urban renewal, land, buildings, or related matters.')}</p></section>
    <section className="analysis-list"><h2>{l('法規搜尋','Regulation Search')}</h2><div className="filter-grid"><label className="search-field"><span>{l('關鍵字','Keyword')}</span><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={l('搜尋標題、類型、日期、代碼或編號','Search title, type, date, code, or ID')}/></label><label><span>{l('法規類型','Regulation type')}</span><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">{l('全部類型','All types')}</option>{types.map(x=><option key={x}>{x}</option>)}</select></label><label><span>{l('起始西元年','From Gregorian year')}</span><input type="number" value={yearFrom} onChange={e=>{setYearFrom(e.target.value);setPage(1)}} /></label><label><span>{l('結束西元年','To Gregorian year')}</span><input type="number" value={yearTo} onChange={e=>{setYearTo(e.target.value);setPage(1)}} /></label><label><span>{l('日期狀態','Date status')}</span><select value={dated} onChange={e=>{setDated(e.target.value);setPage(1)}}><option value="">{l('全部','All')}</option><option value="valid">{l('可解析日期','Valid date')}</option><option value="invalid">{l('未解析日期','Unparseable date')}</option></select></label></div></section>
    <section className="metric-strip">{[[l('來源列數','Source rows'),filtered.length],[l('不重複標題','Unique titles'),new Set(filtered.map(r=>r.title).filter(Boolean)).size],[l('法規類型','Regulation types'),new Set(filtered.map(r=>r.articleType)).size],[l('可解析日期','Valid dates'),filtered.filter(r=>r.hasValidDate).length],[l('最早紀錄日期','Earliest record date'),filtered.filter(r=>r.gregorianDate).sort((a,b)=>(a.gregorianDate??'').localeCompare(b.gregorianDate??''))[0]?.gregorianDate??'—'],[l('最新紀錄日期','Latest record date'),latest?.gregorianDate??'—']].map(([name,value])=><article className="metric" key={String(name)}><span>{name}</span><strong>{value}</strong></article>)}</section>
    <section className="chart-grid"><article className="chart-section"><h2>{l('法規類型','Regulation Types')}</h2><ResponsiveContainer width="100%" height={270}><BarChart data={activeTypes}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="value"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#737d68"/></BarChart></ResponsiveContainer></article><article className="chart-section"><h2>{l('法規時間軸','Regulation Timeline')}</h2><ResponsiveContainer width="100%" height={270}><BarChart data={years}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="value"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#c58a43"/></BarChart></ResponsiveContainer></article><article className="chart-section"><h2>{l('日期完整性','Date Completeness')}</h2><ResponsiveContainer width="100%" height={270}><PieChart><Pie data={[{name:l('可解析','Valid'),value:filtered.filter(r=>r.hasValidDate).length},{name:l('未解析','Unparseable'),value:filtered.filter(r=>!r.hasValidDate).length}]} dataKey="value" nameKey="name" fill="#5f7d9e" label/><Tooltip/></PieChart></ResponsiveContainer></article></section>
    <section className="analysis-list"><h2>{l('資料洞察','Insights')}</h2><p>{latest?l(`篩選結果中最新的來源紀錄日期為 ${latest.gregorianDate}，其類型原始值為 ${latest.articleTypeRaw || '—'}。`,`The latest source-record date in the filtered results is ${latest.gregorianDate}; its original type value is ${latest.articleTypeRaw || '—'}.`):l('目前篩選沒有可解析的紀錄日期。','The current filters contain no parseable record date.')}</p><p>{activeTypes[0]?l(`最常見的來源類型為 ${activeTypes[0].value}，共有 ${activeTypes[0].count} 筆紀錄；此計數不代表重要性或法律效力。`,`The most common source type is ${activeTypes[0].value}, with ${activeTypes[0].count} records; the count does not indicate importance or legal effect.`):'—'}</p></section>
    <section className="analysis-list"><h2>{l('法規目錄','Regulation Directory')}</h2><button className="link-button" onClick={exportCsv}>{l('下載篩選 CSV','Download filtered CSV')}</button><div className="table-wrap"><table><thead><tr>{[l('編號','ID'),l('標題','Title'),l('法規類型','Regulation type'),l('民國日期','ROC date'),l('西元日期（衍生）','Gregorian date (derived)'), 'CountyCode',l('資料狀態','Data status'),l('來源詳情','Source details')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.sourceSequenceNumber||'—'}</td><th>{r.title||'—'} <button className="link-button" onClick={()=>navigator.clipboard?.writeText(r.title)}>{l('複製','Copy')}</button></th><td>{r.articleTypeRaw||'—'}</td><td>{r.rocDateRaw||'—'}</td><td>{r.gregorianDate??'—'}</td><td>{r.countyCodeRaw||'—'}</td><td>{r.hasValidDate?l('可解析日期','Valid date'):l('未解析日期','Unparseable date')}</td><td><details><summary>{l('查看','View')}</summary><pre>{JSON.stringify(r.sourceRaw,null,2)}</pre></details></td></tr>)}</tbody></table></div><nav className="pagination" aria-label="Pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>{l('上一頁','Previous')}</button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>{l('下一頁','Next')}</button></nav></section>
    {summary&&<section className="analysis-list"><h2>{l('資料品質','Data Quality')}</h2><p>{l(`缺少標題 ${summary.dataQuality.missingTitleCount}、缺少編號 ${summary.dataQuality.missingSequenceNumberCount}、重複編號 ${summary.dataQuality.duplicateSequenceNumberCount}、完全重複列 ${summary.dataQuality.exactDuplicateRowCount}、重複標題 ${summary.dataQuality.duplicateTitleCount}、未解析日期 ${summary.invalidDateCount}。`,`Missing titles ${summary.dataQuality.missingTitleCount}; missing IDs ${summary.dataQuality.missingSequenceNumberCount}; duplicate IDs ${summary.dataQuality.duplicateSequenceNumberCount}; exact duplicate rows ${summary.dataQuality.exactDuplicateRowCount}; duplicate titles ${summary.dataQuality.duplicateTitleCount}; unparseable dates ${summary.invalidDateCount}.`)}</p><p>{l(`CountyCode 原始值：${summary.dataQuality.countyCodeValues.join(', ') || '—'}。它是來源行政代碼，未推論為行政區或地理位置。`,`Original CountyCode values: ${summary.dataQuality.countyCodeValues.join(', ') || '—'}. This is an administrative source code; no district or geographic meaning is inferred.`)}</p></section>}
    <section className="analysis-list"><h2>{l('相關資料集','Related modules')}</h2><p>{l('法規資料提供法律與行政脈絡，與房價、租金、交易或土地資料用途不同；不應合併為單一市場指標。','Regulation data provides legal and administrative context and serves a different purpose from housing prices, rents, transaction records, and land data. These datasets should not be combined into a single market indicator.')}</p><p><button className="link-button" onClick={()=>window.dispatchEvent(new CustomEvent('set-dashboard-tab',{detail:8}))}>{l('土地現值','Land values')}</button> <button className="link-button" onClick={()=>window.dispatchEvent(new CustomEvent('set-dashboard-tab',{detail:9}))}>{l('土地使用管制','Land use control')}</button> <button className="link-button" onClick={()=>window.dispatchEvent(new CustomEvent('set-dashboard-tab',{detail:30}))}>{l('公告徵收清冊','Land expropriation registry')}</button></p></section>
    <section className="analysis-list"><h2>{l('資料說明','Data Notes')}</h2><p>{l('資料來源：臺北市資料大平臺「臺北市都市更新相關法規」，提供機關為臺北市都市更新處，更新頻率為不定期。紀錄日期的欄位意義依來源描述，未被解讀為生效、廢止或修正生效日期。','Source: Taipei Open Data Platform, “Taipei Urban Renewal Regulations,” provided by Taipei Urban Redevelopment Office and updated irregularly. The record-date field is not interpreted as an effective, repeal, or amendment-effective date.')}</p><p>{l('法規資料提供法律與行政脈絡，與房價、租金、交易或土地資料用途不同；不應合併為單一市場指標。','Regulation data provides legal and administrative context and serves a different purpose from housing prices, rents, transaction records, and land data. These datasets should not be combined into a single market indicator.')}</p></section>
  </>;
}
